### PR TITLE
Fix parsing left/right-assoc kore terms in kast

### PR DESCRIPTION
**Pull request by gtrepta**
fixes: #3634

### CODE REVIEW

**Comment by gtrepta** [comment]
@radumereuta This is a very small fix, but would you like a test for this?

**Comment by radumereuta** [comment]
Last time I had to modify that file, I added a test: #2766
Maybe you can modify an existing one to account for this case. That way we don't add to the CI time but we test for the problem.

**Comment by gtrepta** [comment]
@radumereuta I found a good place for it. Ready for approval.

**Review by radumereuta — APPROVED** [review]

**Comment by virgil-serbanuta** [comment]
Thanks!

**Pull request merged**
