### PR TITLE
add toml support for pyk options

### PR DESCRIPTION
**Pull request by Baltoli**
Transfer of: https://github.com/runtimeverification/pyk/pull/1008

### CODE REVIEW

**Comment by Baltoli** [comment]
@ovatman The K repository requires that changes are based on the `develop` branch rather than `master`; if you merge `master` into your PR (https://github.com/runtimeverification/k/pull/4254/commits/5fbfaf22d8efde1694fb28565c25d86ab197b9ab) then you'll end up with this versioning noise as well as your actual changes.

**Comment by ehildenb** [comment]
@ovatman you'll need to rebase on `develop` branch directly and remove all the introduce intermediate commits then force push.

**Comment by ovatman** [comment]
> @ovatman you'll need to rebase on `develop` branch directly and remove all the introduce intermediate commits then force push.

@ehildenb 
I did the rebasing yesterday but I didn't force push, I think that's why it didn't seem to work.

**Review by nwatson22 — APPROVED** [review]
This looks good to me, once it has been rebased properly and the KEVM and kontrol branches are working. I like the solution of having the mapping from command-line string format to python variable format.

There may be a way to avoid having to mention all the superclasses in `from_option_string`, by adding a new function in `Options` [here](https://github.com/runtimeverification/k/blob/28bcfb01f5143fcf037db4c64a2868a934b2fefe/pyk/src/pyk/cli/cli.py) similar to the constructor that collects and merges the `from_option_string`s for any type of `Options`.

There is a lot of boilerplate that has to be duplicated across all 3 repos, but this was also the case with version of `Options` that was merged. Hopefully eventually we will be wrapping the argparse and toml parsing logic and consolidating most of the boilerplate into pyk only (Similar to what is mentioned in #4188)

**Pull request merged**
