### PR TITLE
install-build-deps script

### PR DESCRIPTION
**Pull request by 0cjs**
Add an `install-build-deps` script to replace the manual commands in the README. See commit message(s) for details.

__WARNING:__ This commit is based on the commit in #4054; if you merge this it will merge that one too. (The script includes the `libunwind-dev` package added in that commit.)

You'll probably want to do a quick check that this works on MacOS and update the commit message appropriately.

### CODE REVIEW

**Comment by 0cjs** [comment]
This has now been tested on a Mac and fixes applied to make that work properly. (I didn't look closely enough at the Mac code when I was testing on Debian.) It's also been rebased on to the top of the current `main`.

**Comment by Baltoli** [comment]
@0cjs you will need to rebase this PR on the `develop` branch and cut out all the "Set version..." commits; once you've done so CI should run properly for you and we can look at getting this merged. Thanks for the contribution!

**Review by Baltoli — CHANGES_REQUESTED** [review]
Changes look good but PR needs to be rebased.

**Comment by 0cjs** [comment]
It's now rebased.

BTW, I see no harm in you guys just doing this directly (since you're already changing the tracking ("base") branch of the developer's branch anyway. That would help speed things up. (It's reasonable to bail on it if there's any issues doing that, of course, and ask the original developer to fix conflicts or whatever.)

**Review by Baltoli — APPROVED** [review]

**Pull request merged**
