### PR TITLE
Fix a typo in the K standard library

### PR DESCRIPTION
**Pull request by amelieled**
funtional -> total

### CODE REVIEW

**Review by Baltoli — APPROVED** [review]

**Comment by Baltoli** [comment]
Thanks for reopening the PR Amelie! LGTM

**Review by Baltoli — APPROVED** [review]

**Review by dwightguth — APPROVED** [review]
This looks good. We have some technical issues internally relating to pull requests from external collaborators, however, so this can't be merged yet.

You have two options:

1. We could recreate this PR for you and make sure you get credited in the commit message.
2. You can wait until we figure out a solution to these issues.

Let us know which you'd prefer.

**Comment by amelieled** [comment]
I can wait because it is not urgent.

In fact, I have other PRs to open but I opened this one first to make sure I could do a PR (because it was already difficult to do a PR for the Haskell backend).

And I think it's very important that external collaborators can do PRs.

**Comment by amelieled** [comment]
Hi @Baltoli , @ehildenb and @dwightguth !
How much time I'm supposed to wait? Do you think it is possible to fix the problem before the end of the month?

**Comment by Baltoli** [comment]
I'm not sure how much of a change would be required to our CI workflows to implement this @amelieled - I've opened an issue against our devops repo and will update you when we know better what the solution will look like.

**Comment by Baltoli** [comment]
Superseded by https://github.com/runtimeverification/k/pull/3248. @amelieled, please feel free to submit any future PRs to K that you have by following our new CONTRIBUTING.md guidelines, and we'll be able to get them merged far more quickly than this one did. Thanks for your patience.

**Pull request closed without merging**
