### PR TITLE
Packaging: Move `version` into lib/kframework

### PR DESCRIPTION
**Pull request by gtrepta**
For #3675 

We're installing `version` into `/usr/lib/version`. This change moves it to `/usr/lib/kframework/version`.

### CODE REVIEW

**Review by ehildenb — APPROVED** [review]

**Comment by ehildenb** [comment]
Are there any bash scripts that read this file directly? Does `krun --version` call the JVM or just read the file directly, for example?

**Comment by gtrepta** [comment]
> Are there any bash scripts that read this file directly? Does `krun --version` call the JVM or just read the file directly, for example?

The scripts are calling `kompile --version`

**Comment by Robertorosmaninho** [comment]
Actually, `krun`, `kast`, `kompile`, and other tools call this script [k](https://github.com/runtimeverification/k/blob/master/k-distribution/src/main/scripts/lib/k), which is responsible for printing the `--version` by reading it from this file. We don't start the JVM anymore to get the K version.

This modification caused this issue: https://github.com/runtimeverification/k/issues/3690

**Comment by gtrepta** [comment]
Uuuugh. I tested the packaging locally hoping to catch something like this, but the tests must not be covering it.

**Pull request merged**
