### PR TITLE
add #isVariable builtin

### PR DESCRIPTION
**Pull request by daejunpark**

### CODE REVIEW

**Review by denis-bogdanas — APPROVED** [review]
Looks good.

**Comment by daejunpark** [comment]
jenkins: test this please

**Comment by daejunpark** [comment]
@dwightguth Do you have any idea why the test failed?  It failed to build c-semantics, and not sure if it is related to the current change.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Pull request merged**
