### PR TITLE
fix version check in checkJava

### LINKED ISSUE #118: openjdk version confusion in checkJava
When I try to `make` I get a complaint that I don't have a `java` of the required version:

```
~/src/k/latest/evm-semantics(dapphub/stable) » make build-java
== kompile: .build/java/driver-kompiled/timestamp
/home/lev/src/k/latest/evm-semantics/.build/k/k-distribution/target/release/k/bin/kompile --debug --main-module ETHEREUM-SIMULATION --backend java \
				--syntax-module ETHEREUM-SIMULATION .build/java/driver.k --directory .build/java -I .build/java
Error: K requires Java 1.8 to run but the detected version is 10.0.1.
Please either add Java 1.8 bin directory to the PATH or set the JAVA_HOME
environment variable accordingly.
Makefile:131: recipe for target '.build/java/driver-kompiled/timestamp' failed
make: *** [.build/java/driver-kompiled/timestamp] Error 2
```
Indeed, the version reported by `$ java -version` is:
```
~ » java -version
openjdk version "10.0.1" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Debian-4)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Debian-4, mixed mode)
```
So this appears to be some confusion in the Java version number convention. By the way, I am using `openjdk-10-jre 10.0.1+10-4` provided by debian testing. I can only assume that anyone else using debian would have the same problem. The problem is resolved by adjusting `MIN_VERSION` in `k-distribution/src/main/scripts/lib/checkJava`, after that everything builds as expected.

@ehildenb

### PR DESCRIPTION
**Pull request by dwightguth**
Fixes #118 

@livnev if you could confirm that this fixes your issue it would be appreciated.

### CODE REVIEW

**Comment by livnev** [comment]
@dwightguth Can confirm the update to the version check fixes issue #118.  :smiley:

**Comment by livnev** [comment]
On the other hand, I discovered that it won't build if I upgrade all the way to `java-1.11.0-openjdk`, I get a maven error when doing `make k-deps`... :thinking:

**Comment by dwightguth** [comment]
What OS is this? I can confirm that compilation succeeds on a fresh Ubuntu 18.04 with package openjdk-11-jdk once I fix the following issue: https://stackoverflow.com/a/50103533/9848642

That said, apparently openjdk-11-jdk in Ubuntu 18.04 is actually JDK 10? it's a little confusing. I'm testing with Debian Testing now, I'll let you know if I see another issue.

**Comment by dwightguth** [comment]
I can reproduce the issue on debian testing, give me a moment and I should have an updated PR.

**Comment by dwightguth** [comment]
I can confirm that K is broken in JDK 11 update 17 due to a regression in the JDK. since this is the version present in Debian Testing, if you are using this version I would recommend either updating to update 18 if you can, or else use Java 10 for the time being until update 18 rolls out everywhere in package managers. I have been unable to test further in JDK 11 because of this issue so there might be other issues with JDK 11 that I'm not aware of yet. It might work, or it might not. My advice is to use Java 10 for now.

**Comment by dwightguth** [comment]
@ehildenb this should be ready for review.

**Comment by livnev** [comment]
@dwightguth This was on debian testing. I upgraded `openjdk-11-jre` to `11~23-1` (the version in debian unstable) and after pulling in your latest fix to `pom.xml`, was able to build K. :+1: 

Everything seems to work, at least according to `mvn verify -DskipKTest` (`mvn verify` is still running).

**Comment by livnev** [comment]
@dwightguth  `mvn verify` failed some parts, do you know what this could be?

```[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] K Framework Tool Parent 1.0-SNAPSHOT ............... SUCCESS [  2.589 s]
[INFO] K Framework KORE ................................... SUCCESS [  2.413 s]
[INFO] K Framework Tool Kernel ............................ SUCCESS [ 19.421 s]
[INFO] K Framework KTree .................................. SUCCESS [  0.562 s]
[INFO] K Framework Ocaml Backend .......................... SUCCESS [  0.543 s]
[INFO] K Framework Java Backend ........................... SUCCESS [  2.074 s]
[INFO] K Framework Tool Distribution ...................... FAILURE [05:39 min]
[INFO] K Framework API 1.0-SNAPSHOT ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:07 min
[INFO] Finished at: 2018-07-24T20:59:52+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (exec-ktest) on project k-distribution: An Ant BuildException has occured: exec returned: 2
[ERROR] around Ant part ...<exec failonerror="true" dir="/home/lev/src/k/latest/evm-semantics/.build/k/k-distribution" executable="make">... @ 4:113 in /home/lev/src/k/latest/evm-semantics/.build/k/k-distribution/target/antrun/build-main.xml
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :k-distribution
```

**Comment by dwightguth** [comment]
I mean I need to see the entire log, this segment doesn't contain the error.

**Comment by livnev** [comment]
@dwightguth Here's the full output of `mvn verify -e`:
[verifyefaillog.txt](https://github.com/kframework/k/files/2227111/verifyefaillog.txt)

**Comment by dwightguth** [comment]
I am unable to reproduce the error you are reporting on a fresh install of this branch of k on a fresh install of debian testing, and everything seems to be working for me. As such, I'm going to try to get this change merged into master, but you are welcome to open another issue. If you do, please show me the result of running `make` in `k-distribution/tutorial/1_k/2_imp/lesson_1` after running `mvn package`. This test failed for you, but I'm not sure exactly why...

**Review by ehildenb — APPROVED** [review]
Thanks @dwightguth for looking into this!

**Comment by livnev** [comment]
Thanks @dwightguth !

**Pull request merged**
