### PR TITLE
Removed autoimport of definition main module.

### PR DESCRIPTION
**Pull request by traiansf**
This was generating ugly duplication of rules because of bad hashing of rules.  Instead, users will be required to manually include the main module of the definition in the main verification module.  Daejun said that is acceptable.

### CODE REVIEW

**Comment by traiansf** [comment]
Jenkins: test this please

**Comment by daejunpark** [comment]
what's the difference between auto-import and manual-import for the ugly duplication issue?

**Comment by traiansf** [comment]
@daejunpark nothing interesting, really. Just the order in which attributes are serialized as strings, which leads to a hash value being different, too.

**Comment by daejunpark** [comment]
ok, the usage should be fine.  but the code would need @dwightguth's approval.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Review by dwightguth — APPROVED** [review]
Looks fine if this is what the verification team wants.

**Comment by ehildenb** [comment]
Can one of the admins verify this patch?

**Pull request merged**
