### PR TITLE
Global options: Option --cache-file to change default location of parse cache

### PR DESCRIPTION
**Pull request by denis-bogdanas**

### CODE REVIEW

**Comment by denis-bogdanas** [comment]
jenkins: test this please

**Comment by denis-bogdanas** [comment]
P.S. I l also did a refactoring - `GlobalOptions` is now taken from another source in some cases, the old source was incorrect. See the comment in `KompileOptions` for explanation.

**Review by dwightguth — APPROVED** [review]
looks okay so you can merge if the tests pass

**Comment by denis-bogdanas** [comment]
jenkins: test this please

**Pull request merged**
