### PR TITLE
revert mint java code in preparation for mint in k in ocaml backend

### PR DESCRIPTION
**Pull request by dwightguth**

### CODE REVIEW

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Review by traiansf — APPROVED** [review]

**Comment by dwightguth** [comment]
@Andrew-Miranti does this resolve your issue?

**Pull request merged**
