### PR TITLE
Change the `pyk` API docs theme

### PR DESCRIPTION
**Pull request by tothtamas28**
Changes the Sphinx theme from `alabaster` to `sphinx_rtd_theme`, i.e. _Read the Docs_.

To check the generated docs under the new theme, run `make docs` in the `pyk` directory, then open `docs/build/index.html` in a web browser.

### CODE REVIEW

**Comment by tothtamas28** [comment]
Old theme:

image

**Comment by tothtamas28** [comment]
New theme:

image

**Comment by tothtamas28** [comment]
In case someone would like to pick another theme, here's a page that demos some themes available in Sphinx: https://sphinx-themes.readthedocs.io/en/latest/

For me, the most important aspect is how well apidoc sections can be visually separated from each other, e.g. one function signature from the next. In my opinion, _Read the Docs_ looks pretty good in that regard: https://sphinx-themes.readthedocs.io/en/latest/sample-sites/sphinx-rtd-theme/kitchen-sink/api/.

**Review by nwatson22 — APPROVED** [review]

**Review by Baltoli — APPROVED** [review]
Yep, I think this is definitely an improvement. RTD is pretty standard for Python projects in my experience

**Review by gtrepta — APPROVED** [review]

**Pull request merged**
