### PR TITLE
update to new s3 endpoint

### PR DESCRIPTION
**Pull request by dwightguth**

### CODE REVIEW

**Review by eviefp — APPROVED** [review]
I'm not really that familiar with Java/maven, but I did clean my local dependencies and ran a full/clean rebuild and it seems to work. Seems good to me.

**Comment by dwightguth** [comment]
I will merge this when the build finishes and Traian can provide feedback later if there's any suggestions, because I want to get us back up and working again asap.

**Review by traiansf — APPROVED** [review]
Looks good to me

**Comment by dwightguth** [comment]
Jenkins: test this please

**Pull request merged**
