### PR TITLE
Make dryRun output match the real command exactly

### PR DESCRIPTION
**Pull request by phillipharr1s**

### CODE REVIEW

**Review by dwightguth — COMMENTED** [review]
Looks fine to me. I can approve or you can get a kore person to do it, just let me know.

**Comment by phillipharr1s** [comment]
Yeah, please approve.

**Review by dwightguth — APPROVED** [review]

**Comment by phillipharr1s** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Looks like checkstyle failed. You can run src/main/scripts/fix_whitespace on HasksellRewriter.java and it should resolve the issue, although if you have tabs in the file it may mess up the indentation and you should adjust that manually.

**Pull request merged**
