### PR TITLE
Integrate kore-check-functions

### LINKED ISSUE #2135: Integrate kore-check-functions tool into kompile pipeline
The Haskell backend has a tool which can check (for a definition):

- Every equation RHS for a function symbol is a function pattern (what does this mean??? e.g. do the symbols on the RHS all have to be function/functional symbols? Are #Or not allowed? Does the ensures clause have to be defined? Does the pattern have to be linear? Are set variables allowed?)
- Some other thing it checks?

Issue on Kore board: https://github.com/kframework/kore/issues/2472

We should look at how the LLVM backend exhaustiveness check is implemented, and probably implement this check after that one. It should apply to both LLVM and Haskell backend compile.

Also we should check that the exhaustiveness check is called for both backends.

### PR DESCRIPTION
**Pull request by dopamane**
Addresses #2135
Integrates Kore PR [#2840](https://github.com/kframework/kore/pull/2840) 

Questions:
1. Is anything missing?
2. How does the `HaskellCheckFunctions` class get instantiated and used in the Kompile pipeline?
2. How can we verify the tool is being used correctly? Is there a good sample test that we can break to see the functionality?

### CODE REVIEW

**Comment by dopamane** [comment]
@radumereuta

**Comment by radumereuta** [comment]
@dopamane if you look at the last comment in the issue I linked, you can find a description of how this should work.

**Comment by dopamane** [comment]
@radumereuta Ok this is ready for review.

**Review by radumereuta — CHANGES_REQUESTED** [review]
There are no changes since my last message.
Did you forget to push something?
I also think the final version of this should have a test.

**Comment by dopamane** [comment]
@radumereuta  Thank you for the feedback and I apologize for the confusion. I had addressed  the last comment in the linked issue, to the best of my ability, before marking this PR as ready for review. So that is why I did not push anything new, I was waiting for some feedback and clarification on the existing commits. 

Adding an integration test addresses question 1 & 3! I will add a test in the regression-new directory.

Concerning question 2, I determined my confusion about how `kore-check-functions` gets exposed/run was due to always building K with `mvn package -Dhaskell.backend.skip` because I always build Kore separately for development. This caused the `kore-check-functions` binary to not show up in `k-distribution/target/release/k/bin`. Now I am building K with just `mvn package` and I see `kore-check-functions` in `k-distribution/target/release/k/bin` and I can run it. Great, but now I am not sure why we need to add `HaskellCheckFunctions.java`. I had mistakenly thought that `HaskellCheckFunctions.java` was somehow exposing the `kore-check-functions` Kore binary, but I see now that is not the case. It seems the `kore-check-functions` binary is in `k-distribution/target/release/k/bin` regardless of whether `HaskellCheckFunctions.java` exists, just so long as I use `mvn package`. What additional capabilities does `HaskellCheckFunctions.java` provide? Why is it necessary? What is it doing? My best guess is it acts as a wrapper around `kore-check-functions` binary, but I'm not sure why.

P.S. running `mvn verify` on master returns a check-style error, `regression-new/issue-1169/test2.k File has non-Unix line endings or trailing whitespace [RegexpMultiline]`. I usually just `cd` into regression-new and use make for running tests so it doesn't hinder me, but the readme specifies `mvn verify`.

**Comment by radumereuta** [comment]
Ah, I see. Sorry for not paying attention to that.

The first thing you should do is to come up with a small test example. Look through the issue and see what is wrong, and what is the expected behavior. If you have this, then it's easy to know if your modifications are good or not. You can always test.

The second thing is to check if this statement is true:
> Also, if `kore-check-functions` validates the AST anyway, we should just remove the call to `kore-parser`.

That means you have to go to https://github.com/kframework/k/blob/master/haskell-backend/src/main/java/org/kframework/backend/haskell/HaskellBackend.java#L44 and change `kore-parser` to `kore-check-functions`. Those are tools created by the kore team, and I'm not sure about all their functionality.

If that doesn't work, then you will need to call `kore-check-functions` after `kore-parser`. Right now, that tool is being handled by `HaskellBackend.java`. That class is being instantiated by the dependency injection system (google guice). See `HaskellBackendKModule.java`. If it turns out this is what we need to do, then we should meet to discuss the details because there are too many to list here.

**Comment by radumereuta** [comment]
Maybe the failing example should be wrapped in a `runLemma`, `doneLemma` to force the Haskell backend to take at least one step.
You can take a look at this example on how to integrate those: https://github.com/kframework/k/tree/master/k-distribution/tests/regression-new/issue-1879-kproveTrans/haskell

**Comment by radumereuta** [comment]
`[owise]` rules can hurt the java backend. We still have some kevm proofs that need to pass.
@ehildenb please provide some instructions on how to test those before merging.

**Comment by ehildenb** [comment]
To test with KEVM:

```
git clone 'https://github.com/kframework/evm-semantics'
cd evm-semantics
git submodule update --init --recursive
cd deps/k
git fetch --all
git checkout THIS_BRANCH
git submodule update --init --recursive
cd ../..
make deps RELEASE=true
make build -j8
make test-prove TEST_SYMBOLIC_BACKEND=java -j6
```

**Comment by dopamane** [comment]
I was able to successfully run the KEVM tests.

Currently I am investigating why the tool indicates this pair of rules to be matching. The other errors are similar in that the rule pair is: `someRule(K) =>` and `someRule(inj{SomeSort,KItem}(SomeSort))=>`. 
defintion.kore: 854
```
// rule isBool(K)=>#token("false","Bool") requires #token("true","Bool") ensures #token("true","Bool") [owise]
  axiom{R} \implies{R} (
    \and{R} (
      \not{R} (
        \or{R} (
          \exists{R} (Var'Unds'0:SortBool{},
            \and{R} (
              \top{R}(),
              \and{R} (
                \in{SortK{}, R} (
                  X0:SortK{},
                  kseq{}(inj{SortBool{}, SortKItem{}}(Var'Unds'0:SortBool{}),dotk{}())
                ),
                \top{R} ()
              )
          )),
          \bottom{R}()
        )
      ),
      \and{R}(
        \top{R}(),
        \and{R} (
          \in{SortK{}, R} (
            X0:SortK{},
            VarK:SortK{}
          ),
          \top{R} ()
        )
    )),
    \equals{SortBool{},R} (
      LblisBool{}(X0:SortK{}),
     \and{SortBool{}} (
       \dv{SortBool{}}("false"),
        \top{SortBool{}}())))
  [owise{}()]
```
definition.kore: 872
```
// rule isBool(inj{Bool,KItem}(Bool))=>#token("true","Bool") requires #token("true","Bool") ensures #token("true","Bool") 
  axiom{R} \implies{R} (
    \and{R}(
      \top{R}(),
      \and{R} (
          \in{SortK{}, R} (
            X0:SortK{},
            kseq{}(inj{SortBool{}, SortKItem{}}(VarBool:SortBool{}),dotk{}())
          ),
          \top{R} ()
        )),
    \equals{SortBool{},R} (
      LblisBool{}(X0:SortK{}),
     \and{SortBool{}} (
       \dv{SortBool{}}("true"),
        \top{SortBool{}}())))
  []
```

kore-check-functions error:
```
kore-check-functions: [193489] Error (ErrorEquationsSameMatch):
    Matching equation(s):
    Equations

    definition.kore 872:7
        requires:
            /* D Sfa */ \top{_}()
        argument:
            /* Spa */
            \in{SortK{}, _}(
                /* Fl Fn D Sfa */ EquationX0:SortK{},
                /* Fl Fn D Spa */
                kseq{}(
                    /* Fl Fn D Spa */
                    /* Inj: */ inj{SortBool{}, SortKItem{}}(
                        /* Fl Fn D Sfa */ EquationVarBool:SortBool{}
                    ),
                    /* Fl Fn D Sfa Cl */ dotk{}()
                )
            )
        antiLeft:
            
        left:
            /* Fl Fn D Spa */ LblisBool{}(/* Fl Fn D Sfa */ EquationX0:SortK{})
        right:
            /* Fl Fn D Sfa Cl */ \dv{SortBool{}}("true")
        ensures:
            /* D Sfa */ \top{_}()
    and

    definition.kore 854:7
        requires:
            /* D Sfa */ \top{_}()
        argument:
            /* Spa */
            \in{SortK{}, _}(
                /* Fl Fn D Sfa */ EquationX0:SortK{},
                /* Fl Fn D Sfa */ EquationVarK:SortK{}
            )
        antiLeft:
            /* Spa */
            \not{_}(
                /* Spa */
                \exists{_}(
                    EquationVar'Unds'0:SortBool{},
                    /* Spa */
                    \in{SortK{}, _}(
                        /* Fl Fn D Sfa */ EquationX0:SortK{},
                        /* Fl Fn D Spa */
                        kseq{}(
                            /* Fl Fn D Spa */
                            /* Inj: */ inj{SortBool{}, SortKItem{}}(
                                /* Fl Fn D Sfa */ EquationVar'Unds'0:SortBool{}
                            ),
                            /* Fl Fn D Sfa Cl */ dotk{}()
                        )
                    )
                )
            )
        left:
            /* Fl Fn D Spa */ LblisBool{}(/* Fl Fn D Sfa */ EquationX0:SortK{})
        right:
            /* Fl Fn D Sfa Cl */ \dv{SortBool{}}("false")
        ensures:
            /* D Sfa */ \top{_}()
    match the same term.
```
`inj`:
```
module INJ
    symbol inj{From, To}(From) : To [sortInjection{}()]
    axiom {S1, S2, S3, R} \equals{S3, R}(inj{S2, S3}(inj{S1, S2}(T:S1)), inj{S1, S3}(T:S1)) [simplification{}()]
endmodule
```

Update:
I've modified the check-functions tool to display the simplified predicate in the error message. Hopefully this will ease debugging.
```
        \and{SortBool{}}(
            /* term: */
            /* D Sfa */ \top{SortBool{}}(),
        \and{SortBool{}}(
            /* predicate: */
            /* Sfa */
            \not{SortBool{}}(
                /* Spa */
                \and{SortBool{}}(
                    /* Spa */
                    \ceil{SortBool{}, SortBool{}}(
                        /* Fl Fn D Sfa */ EquationVarBool:SortBool{}
                    ),
                    /* Spa */
                    \equals{SortBool{}, SortBool{}}(
                        /* Fl Fn D Sfa */ EquationVarBool:SortBool{},
                        /* Fl Fn D Sfa */ EquationVarBool:SortBool{}
                    )
                )
            ),
            /* substitution: */
            \and{SortBool{}}(
                /* Spa */
                \equals{SortK{}, SortBool{}}(
                    /* Fl Fn D Sfa */ EquationVarK:SortK{},
                    /* Fl Fn D Sfa */
                    kseq{}(
                        /* Fl Fn D Sfa */
                        /* Inj: */ inj{SortBool{}, SortKItem{}}(
                            /* Fl Fn D Sfa */ EquationVarBool:SortBool{}
                        ),
                        /* Fl Fn D Sfa Cl */ dotk{}()
                    )
                ),
                /* Spa */
                \equals{SortK{}, SortBool{}}(
                    /* Fl Fn D Sfa */ EquationX0:SortK{},
                    /* Fl Fn D Sfa */
                    kseq{}(
                        /* Fl Fn D Sfa */
                        /* Inj: */ inj{SortBool{}, SortKItem{}}(
                            /* Fl Fn D Sfa */ EquationVarBool:SortBool{}
                        ),
                        /* Fl Fn D Sfa Cl */ dotk{}()
                    )
                )
            )
        ))
```

**Comment by ana-pantilie** [comment]
@dopamane Are those equations generated by the frontend?

**Comment by dopamane** [comment]
Yes, they are generated. Relevant manual section: https://kframework.org/USER_MANUAL/#projection-and-predicate-functions . Simplify rules by hand (possible to just print simplified equations?). They include `owise` so it is different from the previous `andBool`, `orBool` etc. errors.

**Comment by radumereuta** [comment]
Please reopen when things advance in this direction.

**Pull request closed without merging**
