### PR TITLE
Fix decodeKoreString again

### LINKED ISSUE #2356: Kore variable name encoding discussion
Right now `encodeStringToAlphanumeric` and `decodeKoreString` are not implemented properly.
let's discuss in the meeting what is the best approach here since we would like the kore encoding to be somewhat readable.

`'Unds'V'Unds'9` -> `_V_9`
`'QuesUnds'0` -> `?_0`

### PR DESCRIPTION
**Pull request by radumereuta**
Fixes: #2356
I followed the idea from the llvm backend.
I found some differences in encoding though: `LT` -> `-LT-` and so on...
Please confirm this is the expected behavior.

### CODE REVIEW

**Review by ehildenb — APPROVED** [review]

**Comment by radumereuta** [comment]
@dwightguth I would like you to confirm that the current encoding is what the llvm backend expected. And why wasn't there anything failing before?

**Comment by dwightguth** [comment]
This seems fine, but you should take a look at where this code is called from and make sure it's being adequately tested.

**Comment by ehildenb** [comment]
@radumereuta maybe related: https://runtimeverification.slack.com/archives/CC360GUTG/p1639035350293100

**Review by ehildenb — APPROVED** [review]

**Comment by ehildenb** [comment]
LGTM, feel free to automerge or wait for more reviews. Thanks for the tests!

**Pull request merged**
