### PR TITLE
Expose pyk term minimizer to command line

### PR DESCRIPTION
**Pull request by ehildenb**
I will use this to print out minimized terms from the prover, so I don't have to scroll through miles of configuration to see the needed state.

### CODE REVIEW

**Comment by ehildenb** [comment]
I've confirmed that this works on KEVM. it takes output like this:

```  #Ceil ( #roundpower ( COLLECTED +Int BAL , 90 , 100 , ( NOW -Int START ) /Int 31536000 ) )                                                                                                                         
#And                                                                                                      
  #Not ( {                                           
    #roundpower ( COLLECTED +Int BAL , 90 , 100 , ( NOW -Int START ) /Int 31536000 ) *Int 10 /Int 100 *Int ( ( NOW -Int START ) modInt 31536000 /Int 31536000 ) +Int COLLECTED +Int BAL -Int #roundpower ( COLLECTED 
+Int BAL , 90 , 100 , ( NOW -Int START ) /Int 31536000 )                                                  
  #Equals                                            
    chop ( #roundpower ( COLLECTED +Int BAL , 90 , 100 , ( NOW -Int START ) /Int 31536000 ) *Int 10 /Int 100 *Int ( ( NOW -Int START ) modInt 31536000 /Int 31536000 ) +Int COLLECTED +Int BAL -Int #roundpower ( COL
LECTED +Int BAL , 90 , 100 , ( NOW -Int START ) /Int 31536000 ) )                                         
  } )                                                
#And                                                 
  <kevm>                                                                                                                                                                                                             
    <k>                                                                                                                                                                                                              
      doneLemma ( chop ( #roundpower ( COLLECTED +Int BAL , 90 , 100 , ( NOW -Int START ) /Int 31536000 ) *Int 10 /Int 100 *Int ( ( NOW -Int START ) modInt 31536000 /Int 31536000 ) +Int COLLECTED +Int BAL -Int #ro
undpower ( COLLECTED +Int BAL , 90 , 100 , ( NOW -Int START ) /Int 31536000 ) ) ) ~> _DotVar2 ~> .                                                                                                                   
    </k>                                                                                                                                                                                                             
    <exit-code>                                                                                                                                                                                                      
      _4                                             
    </exit-code>                                     
    <mode>                                           
      _5                                             
    </mode>                                          
    <schedule>                                       
      _6                                             
    </schedule>                                      
    <ethereum>                                       
      <evm>                                          
        <output>                                     
          _7                                         
        </output>                                    
        <statusCode>                                 
          _8                                         
        </statusCode>                                
        <endPC>                                      
          _9                                         
        </endPC>                                     
        <callStack>                                  
          _10                                        
        </callStack>                                 
        <interimStates>                              
          _11                                        
        </interimStates>                             
        <touchedAccounts>                            
          _12                                        
        </touchedAccounts>                        <callState>                                                                                                                                                                                        [191/1193]
          <program>                                  
            _13                                      
          </program>                                 
          <jumpDests>                                
            _14                                      
          </jumpDests>                               
          <id>                                       
            _15                                      
          </id>                                      
          <caller>                                   
            _16                                      
          </caller>                                  
          <callData>                                 
            _17                                      
          </callData>                                
          <callValue>                                
            _18                                      
          </callValue>                               
          <wordStack>                                
            _19                                      
          </wordStack>                               
          <localMem>                                 
            _20                                      
          </localMem>                                
          <pc>                                       
            _21                                      
          </pc>                                      
          <gas>                                      
            _22                                      
          </gas>                                     
          <memoryUsed>                               
            _23                                      
          </memoryUsed>                              
          <callGas>                                  
            _24                                      
          </callGas>                                 
          <static>                                   
            _25                                      
          </static>                                  
          <callDepth>                                
            _26                                      
          </callDepth>                               
        </callState>                                 
        <substate>                                   
          <selfDestruct>                             
            _27                                      
          </selfDestruct>                            
          <log>                                      
            _28                                      
          </log>                                     
          <refund>                                   
            _29                                      
          </refund>                                  
        </substate>                                  
        <gasPrice>                                   
          _30                                      </gasPrice>                                                                                                                                                                                                  
        <origin>                                                                                                                                                                                                     
          _31                                                                                                                                                                                                        
        </origin>                                                                                                                                                                                                    
        <blockhashes>                                                                                                                                                                                                
          _32                                                                                                                                                                                                        
        </blockhashes>                                                                                                                                                                                               
        <block>                                      
          <previousHash>                             
            _33                                      
          </previousHash>                            
          <ommersHash>                               
            _34                                      
          </ommersHash>                              
          <coinbase>                                 
            _35                                      
          </coinbase>                                
          <stateRoot>                                
            _36                                      
          </stateRoot>                               
          <transactionsRoot>                         
            _37                                      
          </transactionsRoot>                        
          <receiptsRoot>                             
            _38                                      
          </receiptsRoot>                            
          <logsBloom>                                
            _39                                      
          </logsBloom>                               
          <difficulty>                               
            _40                                      
          </difficulty>                              
          <number>                                   
            _41                                      
          </number>                                  
          <gasLimit>                                 
            _42                                      
          </gasLimit>                                
          <gasUsed>                                  
            _43                                      
          </gasUsed>                                 
          <timestamp>                                
            _44                                      
          </timestamp>                               
          <extraData>                                
            _45                                      
          </extraData>                               
          <mixHash>                                  
            _46                                      
          </mixHash>                                 
          <blockNonce>                               
            _47                                      
          </blockNonce>                               <ommerBlockHeaders>                        
            _48                                      
          </ommerBlockHeaders>                       
        </block>                                     
      </evm>                                         
      <network>                                      
        <chainID>                                    
          _49                                        
        </chainID>                                   
        <activeAccounts>                             
          _50                                        
        </activeAccounts>                            
        <accounts>                                   
          _51                                        
        </accounts>                                  
        <txOrder>                                    
          _52                                        
        </txOrder>                                   
        <txPending>                                  
          _53                                        
        </txPending>                  <messages>                                   
          _54                                        
        </messages>                                  
      </network>                                     
    </ethereum>                                      
  </kevm>                                            
#And                                                 
  {                                                  
    true                                             
  #Equals                                            
    0 <=Int BAL                                      
  }                                                  
#And                                                 
  {                                                  
    true                                             
  #Equals                                            
    0 <=Int COLLECTED                                
  }                                                  
#And                                                 
  {                                                  
    true                                             
  #Equals                                            
    0 <=Int NOW                                      
  }                                                  
#And                                                 
  {                                                  
    true                                             
  #Equals                                            
    0 <=Int NOW -Int START                           
  }                                                  
#And                                                 
  {                                                  
    true                                             
  #Equals                                            
    0 <=Int START                                    
  }                                                  
#And                                                 
  {                                                  
    true                                             
  #Equals                                            
    0 <Int NOW -Int START                            
  }                                                  
#And                                                 
  {                                                  
    true                                             
  #Equals                                            
    #accumulatedReleasedTokens ( BAL , COLLECTED , START , NOW ) <Int BAL +Int COLLECTED +Int -10
  }                                                  
#And                                                                                                                                                                                                                 
  {                                                                                                                                                                                                                  
    true                                             
  #Equals                                            
    #accumulatedReleasedTokens ( BAL , COLLECTED , START , NOW ) >Int COLLECTED +Int 3                    
  }                                                  
#And                                                 
  {                                                  
    true                                             
  #Equals                                            
    ( COLLECTED +Int BAL ) *Int 3153600 <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936
  }                                                  
#And                                                 
  {                                                  
    true                                             
  #Equals                                            
    BAL <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936               
  }                                                  
#And                                                 
  {                                                  
    true                                             
  #Equals                                            
    COLLECTED <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936
  }                                                  
#And                                                 
  {                                                  
    true                                             
  #Equals                                            
    NOW -Int START <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936
  }                                                  
#And                                                 
  {                                                  
    true                                             
  #Equals                                            
    NOW <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936               
  }                                                  
#And                                                 
  {                                                  
    true                                             
  #Equals                                            
    START <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936             
  }                                        
```

and instead prints this:

```
#Ceil( #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) ) #And #Not( { #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) *Int 10 /Int 100 *Int NOW -Int START modInt 31536000 /Int 31536000 +Int COLLECTED +Int BAL -Int #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) #Equals chop( #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) *Int 10 /Int 100 *Int NOW -Int START modInt 31536000 /Int 31536000 +Int COLLECTED +Int BAL -Int #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) ) } ) #And <generatedTop>
  <kevm>
    <k>
          doneLemma( chop( #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) *Int 10 /Int 100 *Int NOW -Int START modInt 31536000 /Int 31536000 +Int COLLECTED +Int BAL -Int #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) ) )
      ~> _DotVar2
    </k>
    ...
  </kevm>
  ...
</generatedTop> #And { true #Equals 0 <=Int BAL } #And { true #Equals 0 <=Int COLLECTED } #And { true #Equals 0 <=Int NOW } #And { true #Equals 0 <=Int NOW -Int START } #And { true #Equals 0 <=Int START } #And { true #Equals 0 <Int NOW -Int START } #And { true #Equals #accumulatedReleasedTokens( BAL , COLLECTED , START , NOW ) <Int BAL +Int COLLECTED +Int -10 } #And { true #Equals #accumulatedReleasedTokens( BAL , COLLECTED , START , NOW ) >Int COLLECTED +Int 3 } #And { true #Equals COLLECTED +Int BAL *Int 3153600 <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936 } #And { true #Equals BAL <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936 } #And { true #Equals COLLECTED <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936 } #And { true #Equals NOW -Int START <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936 } #And { true #Equals NOW <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936 } #And { true #Equals START <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936 }
```

**Comment by ehildenb** [comment]
With the addition of the `opinionated` argument to `buildSymbolTable`, the output now looks like:

```
#Ceil( #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) )
#And #Not( { #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) *Int 10 /Int 100 *Int NOW -Int START modInt 31536000 /Int 31536000 +Int COLLECTED +Int BAL -Int #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) #Equals chop( #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) *Int 10 /Int 100 *Int NOW -Int START modInt 31536000 /Int 31536000 +Int COLLECTED +Int BAL -Int #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) ) } )
#And <generatedTop>
  <kevm>
    <k>
          doneLemma( chop( #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) *Int 10 /Int 100 *Int NOW -Int START modInt 31536000 /Int 31536000 +Int COLLECTED +Int BAL -Int #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) ) )
      ~> _DotVar2
    </k>
    ...
  </kevm>
  ...
</generatedTop>
#And { true #Equals 0 <=Int BAL }
#And { true #Equals 0 <=Int COLLECTED }
#And { true #Equals 0 <=Int NOW }
#And { true #Equals 0 <=Int NOW -Int START }
#And { true #Equals 0 <=Int START }
#And { true #Equals 0 <Int NOW -Int START }
#And { true #Equals #accumulatedReleasedTokens( BAL , COLLECTED , START , NOW ) <Int BAL +Int COLLECTED +Int -10 }
#And { true #Equals #accumulatedReleasedTokens( BAL , COLLECTED , START , NOW ) >Int COLLECTED +Int 3 }
#And { true #Equals COLLECTED +Int BAL *Int 3153600 <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936 }
#And { true #Equals BAL <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936 }
#And { true #Equals COLLECTED <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936 }
#And { true #Equals NOW -Int START <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936 }
#And { true #Equals NOW <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936 }
#And { true #Equals START <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936 }
```

must easier to read

**Comment by ehildenb** [comment]
With the addition of the `opinionated` argument to `buildSymbolTable`, the output now looks like:

```
#Ceil( #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) )
#And #Not( { #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) *Int 10 /Int 100 *Int NOW -Int START modInt 31536000 /Int 31536000 +Int COLLECTED +Int BAL -Int #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) #Equals chop( #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) *Int 10 /Int 100 *Int NOW -Int START modInt 31536000 /Int 31536000 +Int COLLECTED +Int BAL -Int #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) ) } )
#And <generatedTop>
  <kevm>
    <k>
          doneLemma( chop( #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) *Int 10 /Int 100 *Int NOW -Int START modInt 31536000 /Int 31536000 +Int COLLECTED +Int BAL -Int #roundpower( COLLECTED +Int BAL , 90 , 100 , NOW -Int START /Int 31536000 ) ) )
      ~> _DotVar2
    </k>
    ...
  </kevm>
  ...
</generatedTop>
#And { true #Equals 0 <=Int BAL }
#And { true #Equals 0 <=Int COLLECTED }
#And { true #Equals 0 <=Int NOW }
#And { true #Equals 0 <=Int NOW -Int START }
#And { true #Equals 0 <=Int START }
#And { true #Equals 0 <Int NOW -Int START }
#And { true #Equals #accumulatedReleasedTokens( BAL , COLLECTED , START , NOW ) <Int BAL +Int COLLECTED +Int -10 }
#And { true #Equals #accumulatedReleasedTokens( BAL , COLLECTED , START , NOW ) >Int COLLECTED +Int 3 }
#And { true #Equals COLLECTED +Int BAL *Int 3153600 <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936 }
#And { true #Equals BAL <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936 }
#And { true #Equals COLLECTED <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936 }
#And { true #Equals NOW -Int START <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936 }
#And { true #Equals NOW <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936 }
#And { true #Equals START <Int 115792089237316195423570985008687907853269984665640564039457584007913129639936 }
```

must easier to read

**Review by radumereuta — APPROVED** [review]
Still not convinced that `opinionated` is the most descriptive name for what you are doing here, but the code looks fine.

**Review by Baltoli — APPROVED** [review]
Looks good to me

**Pull request merged**
