### PR TITLE
Addded Scala kore parser and Kore2K translator and integrated them into K

### PR DESCRIPTION
**Pull request by traiansf**

### CODE REVIEW

**Comment by traiansf** [comment]
@dwightguth only the last commit is relevant; the rest are just history imported from the kore repository.

**Review by dwightguth — CHANGES_REQUESTED** [review]
Please see my comments on the last commit. I have some minor suggestions and also a few recommendations on how to translate kore back into k.

**Comment by traiansf** [comment]
@dwightguth I think I've addresses all your recommendations.  Sorry for not understanding what you meant earlier;  I had just woken up.

**Review by dwightguth — APPROVED** [review]

**Comment by dwightguth** [comment]
this is good enough, so I approved. Note however that what I actually suggested was to make TextToKore's interface be static. (ie, in scala, to say `object TextToKore { def apply(...) = ... }`)

**Pull request merged**
