### PR TITLE
k-distribution/: rename unification.k => symbolic.k

### PR DESCRIPTION
**Pull request by ehildenb**
Generalization of the file `unification.k` to allow other symbolic reasoning.

### CODE REVIEW

**Comment by dwightguth** [comment]
I'm okay with renaming this, but you should probably keep the old filename for backwards compatibility.

**Comment by ehildenb** [comment]
@dwightguth do you mean have a symlink, or just re-purpose the file without renaming?

**Comment by dwightguth** [comment]
I mean just add a file with the old file name that requires the new file name.

**Comment by ehildenb** [comment]
@dwightguth done

**Comment by ehildenb** [comment]
Jenkins: test this please

**Pull request closed without merging**
