### PR TITLE
kernel: option --timeout: support for kserver mode

### PR DESCRIPTION
**Pull request by denis-bogdanas**

### CODE REVIEW

**Review by dwightguth — CHANGES_REQUESTED** [review]
I'm not really sure why we're not just calling System.exit regardless of whether or not we are nailgun. Interrupting the main thread does not sound to me like it would be sufficient to get K to fully terminate if there are other threads associated with that nail.

**Comment by denis-bogdanas** [comment]
Because timeout is for current task, not for entire kserver. There are usage scenarios in which some `kprove` commands are expected to timeout. We want the other commands to continue running.

**Comment by dwightguth** [comment]
It will. We currently call System.exit after every frontend finishes, even when we are running a nail.

**Comment by denis-bogdanas** [comment]
But in this case `System.exit()` is getting called from another thread than the nail - from the timeout thread. Will it know what nail to stop? Are the timeout thread and nail main thread linked by a common thread group?

**Comment by dwightguth** [comment]
I think you're right that System.exit will not know what to do about this case, so thanks for pointing that out. I thought it would be handled on the basis of the parent thread, but it seems it's not. That being said, I still suspect that interrupting the main thread will not necessarily stop any threads that were spawned by that thread... This needs more investigation.

**Comment by dwightguth** [comment]
Has this been tested? I took a look at the nailgun code and I wouldn't have expected this particular change to work, after having looked closer (contrary to what I thought earlier). I'd like to make sure that we've actually tested it before merging it.

**Comment by denis-bogdanas** [comment]
There might be some problems with this PR so it's not ready yet. And I will test it in Nailgun to make sure it works.

**Comment by ehildenb** [comment]
Re-open if needed.

**Pull request closed without merging**
