### PR TITLE
split builtin MAP into concrete vs symbolic

### PR DESCRIPTION
**Pull request by dfilaretti**
As we are doing for other modules, let's split `MAP` into "concrete" and "symbolic" components. 
For now, everything stays the same except for `_[_] orDefault _ `.

### CODE REVIEW

**Review by dwightguth — CHANGES_REQUESTED** [review]
What? No. We don't need anything like this. You can add the axiom directly to the MAP module if you want to have an axiomatization of lookupOrDefault.a

**Comment by dfilaretti** [comment]
Looks like this is now causing a regression? 
```
/bin/krun tests/sorting.kool --output none  -d . | diff - tests/sorting.kool.out
     [exec] make: *** [tests/regression-new] Error 2
     [exec] make: *** Waiting for unfinished jobs....
     [exec] make[2]: Leaving directory '/var/lib/jenkins/jobs/rv-k-pull-request/workspace/k-pr/k-distribution/tests
```

**Review by dwightguth — APPROVED** [review]

**Comment by dfilaretti** [comment]
Actually, this seems to be the error: 

```
[exec] cat tests/free-variable-capture.lambda.in 2>/dev/null | /var/lib/jenkins/jobs/rv-k-pull-request/workspace/k-pr/k-distribution/bin/krun tests/free-variable-capture.lambda --search --pattern "<k> V:K </k>"  -d . | diff - tests/free-variable-capture.lambda.out
     [exec] [Error] Compiler: Had 1 parsing errors.
     [exec] [Error] Compiler: Module Map must be visible at the configuration declaration,
     [exec] in module A
     [exec] make[2]: *** [a-kompiled/timestamp] Error 113
     [exec] make[1]: *** [proj-attribute] Error 2
     [exec] make[1]: *** Waiting for unfinished jobs....
     [exec] ../../../include/ktest.mak:32: recipe for target 'a-kompiled/timestamp' failed
     [exec] make[2]: Leaving directory '/var/lib/jenkins/jobs/rv-k-pull-request/workspace/k-pr/k-distribution/tests
```

So it shouldn't probably be merged...

**Comment by dfilaretti** [comment]
@dwightguth I know you approved this a couple of days ago, but Jenkins keeps failing (see my previous comment). What can you recommend doing? I think I didn't get errors in my first version of this patch btw.

**Comment by dfilaretti** [comment]
Failing with a new error this time (after having "merged with master"): 

```
FATAL: command execution failed
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2679)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3154)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:862)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.Command.readFrom(Command.java:140)
	at hudson.remoting.Command.readFrom(Command.java:126)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
Caused: java.io.IOException: Backing channel 'rvwork-2-big-jenkins-container' is disconnected.
	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:214)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:283)
	at com.sun.proxy.$Proxy92.isAlive(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1137)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1129)
	at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:155)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:109)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1815)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
FATAL: Unable to delete script file /tmp/jenkins4356530139075343959.sh
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2679)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3154)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:862)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.Command.readFrom(Command.java:140)
	at hudson.remoting.Command.readFrom(Command.java:126)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
Caused: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on rvwork-2-big-jenkins-container failed. The channel is closing down or has closed down
	at hudson.remoting.Channel.call(Channel.java:948)
	at hudson.FilePath.act(FilePath.java:1089)
	at hudson.FilePath.act(FilePath.java:1078)
	at hudson.FilePath.delete(FilePath.java:1582)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:123)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1815)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Execute shell' marked build as failure
ERROR: Step ‘Archive the artifacts’ failed: no workspace for rv-k-pull-request #666
Performing Post build task...
Match found for :INFO : True
Logical operation result is TRUE
Running script  : ${WORKSPACE}/k-pr/k-distribution/target/release/k/bin/stop-kserver || echo "not running"
export KSERVER_SOCKET="${WORKSPACE}/k-pr/k-exercises/tutorial/kserver"
${WORKSPACE}/k-pr/k-distribution/target/release/k/bin/stop-kserver || echo "not running"

Exception when executing the batch command : no workspace from node hudson.slaves.DumbSlave[rvwork-2-big-jenkins-container] which is computer hudson.slaves.SlaveComputer@7997d37c and has channel null
Build step 'Post build task' marked build as failure
Setting status of 84f93cdec71012c6ac6a0410e7e7311d3ec6afc6 to FAILURE with url http://office.runtimeverification.com/jenkins/job/rv-k-pull-request/666/ and message: ' '
Finished: FAILURE

```

**Comment by dwightguth** [comment]
This is because rvwork2 is currently flaky. Run it on rvwork1 for now instead

**Comment by dfilaretti** [comment]
@dwightguth How am I supposed to run it on rvwork1?

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dfilaretti** [comment]
OK, looks like there's still the following error:

```
[exec] [Error] Compiler: Had 1 parsing errors.
     [exec] [Error] Compiler: Module Map must be visible at the configuration declaration,
     [exec] in module A
     [exec] make[2]: *** [a-kompiled/timestamp] Error 113
     [exec] make[1]: *** [proj-attribute] Error 2
     [exec] make[1]: *** Waiting for unfinished jobs....
     [exec] ../../../include/ktest.mak:32: recipe for target 'a-kompiled/timestamp' failed
     [exec] make[2]: Leaving directory '/mnt/hd2/rvpslave/workspace/rv-k-pull-request/k-distribution
```

And there's also a parsing ambiguity:

```
 [exec] [Warning] Inner Parser: Parsing ambiguity. Arbitrarily choosing the first.
     [exec] 1: syntax Bytes ::= ".Bytes"
     [exec]     .Bytes_BYTES-IN-K(...)
     [exec] 2: syntax Bytes ::= ".Bytes"
     [exec]     .Bytes_BYTES-HOOKED(...)
     [exec] 	Source(/mnt/hd2/rvpslave/workspace/rv-k-pull-request/k-distribution/target/release
```

A few days ago Darko suggested there's a possibility we could have a Jenkins problem somewhere, but given that this is now running on a different server and we still get the same error, can I safely assume this is a genuine error that should be fixed? @dwightguth 

EDIT: however I can't see the errors on my machine (using `mvn package`), so I am a bit confused now.

**Comment by dwightguth** [comment]
The parsing ambiguity is a known issue, shouldn't be related to this change. It doesn't make the test fail so don't worry about that. It's the other issue that you need to fix.

**Comment by ehildenb** [comment]
Can one of the admins verify this patch?

**Comment by dwightguth** [comment]
Closing as we are not going in this direction with the prelude.

**Pull request closed without merging**
