### PR TITLE
Configuration formatting improvements

### PR DESCRIPTION
**Pull request by nishantjr**
This change allows use to use format attributes as cell properties, and improves pretty printing of Map, List and Set cells.

We can now do write `configuration <foo  format="foo(%2)"> ... </foo>` to have K pretty print the configuration as `foo(...)`.

### CODE REVIEW

**Comment by dwightguth** [comment]
looks like you need to update the unit test for the transformer.

**Comment by nishantjr** [comment]
@dwightguth Yes, done.

What kind of integration tests would you like? I had expected that I'd just have to change existing tests that use Map cells etc, but none seem to have failed (at least on my machine).

**Comment by dwightguth** [comment]
you just need to write a test with a configuration with one of each type of cell collection and one cell with a custom format attribute, and then execute some program in that semantics, even if it takes zero steps.

**Comment by dwightguth** [comment]
Also, don't forget to sign the CLA.

**Comment by nishantjr** [comment]
@dwightguth For some reason the format attribute for MapItem etc is ignored by the Java backend (but not ocaml). Any suggestions?

**Comment by dwightguth** [comment]
The cell collections are not handled properly on the java backend and are transformed into terms of sort List/Map/Set. There's not really anything you can do about this... it's too complicated and ingrained a change to make.

**Comment by nishantjr** [comment]
@dwightguth  Ok. This is ready for your review now.

**Comment by dwightguth** [comment]
I'm not going to review this yet because I want #432 to be merged first as it includes a much better change to the regressions-new/Makefile that is going to conflict with your changes. Will take a look once that's merged and you resolve conflicts though.

**Comment by nishantjr** [comment]
Great. I like that change.

**Review by dwightguth — APPROVED** [review]

**Pull request merged**
