### PR TITLE
add [matching] attribute

### PR DESCRIPTION
**Pull request by daejunpark**
https://github.com/runtimeverification/verified-smart-contracts/pull/52#issuecomment-427107247

### CODE REVIEW

**Comment by daejunpark** [comment]
@dwightguth It should be ready to review once #55 is merged.

**Comment by daejunpark** [comment]
@dwightguth it is ready to review. it contains several kprover improvements, including the one related to #55 that @ehildenb suggested.

**Review by dwightguth — CHANGES_REQUESTED** [review]
Everett said he wanted a test, but otherwise this looks fine.

**Comment by daejunpark** [comment]
@dwightguth Tests are added. Please merge if you're happy with it.

**Review by dwightguth — APPROVED** [review]
Since this only touches the java backend, I haven't gone over it in depth, but it seems fine to me.

**Pull request merged**
