### PR TITLE
Fix another checkstyle issue

### PR DESCRIPTION
**Pull request by chathhorn**

### CODE REVIEW

**Comment by chathhorn** [comment]
Jenkins: test this please

**Comment by chathhorn** [comment]
Jenkins: test this please

**Comment by chathhorn** [comment]
Jenkins: test this please

**Comment by chathhorn** [comment]
Jenkins: test this please

**Comment by chathhorn** [comment]
Jenkins: test this please

**Review by ehildenb — APPROVED** [review]

**Pull request merged**
