### PR TITLE
BinaryLoader: lock parse cache file before saving the cache

### PR DESCRIPTION
**Pull request by denis-bogdanas**
Eliminates ObjectInputStream exceptions when several K instances run in parallel over same definition.

Tested on verified-smart-contracts.

Essentially only one line matters:
```
out.getChannel().lock();
```
Everything else is refactoring.

### CODE REVIEW

**Review by dwightguth — COMMENTED** [review]
Have you tested this with multiple instances of kompile running concurrently that use --cache-file?

**Comment by denis-bogdanas** [comment]
No, just multiple instances of kprove. Why would you run multiple instances of kompile over the same destination dir? If they run over different destinations, then each has its own cache file and there is no race condition.

**Comment by dwightguth** [comment]
What I want to test is multiple different K definitions that compile to different directories but share the same cache file and have some files in common.

**Comment by denis-bogdanas** [comment]
No I didn't test that but this fix should make them work properly. It doesn't matter who rewrites the cache after all - kprove or kompile.

**Comment by dwightguth** [comment]
Okay, I will approve this and then try it once it's merged.

**Review by dwightguth — APPROVED** [review]

**Pull request merged**
