### PR TITLE
Fix issue with special characters in path

### LINKED ISSUE #3179: Uncaught exception thrown of type InvalidPathException because of accents in the path name
### What component is the issue in?

None

### Which command

- [X] kompile
- [ ] kast
- [ ] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

K version:    v5.5.102

### Operating System

Linux / K is installed with `sudo apt install ./kframework_...`

### K Definitions (If Possible)

Any K definition

### Steps to Reproduce

`cd Téléchargements/` (download in French :p)
`kompile toto.k`

### Expected Results

[Error] Internal: Uncaught exception thrown of type InvalidPathException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/runtimeverification/k/issues
(InvalidPathException: Malformed input or input contains unmappable characters:
~/T��l��chargements/./toto.k)

### PR DESCRIPTION
**Pull request by radumereuta**
Fixes #3179
Because numbers are being treated differently in other languages, we restrict them to en_US.UTF-8

### CODE REVIEW

**Review by Baltoli — APPROVED** [review]

**Review by Baltoli — APPROVED** [review]
Looks good; I will let @Robertorosmaninho approve and automerge

**Review by Robertorosmaninho — COMMENTED** [review]
We may get this warning:
```
setenv: line 24: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
```

Install `language-pack-en` solved it for me. Should we add it as a dependence, @radumereuta?
```
apt-get install language-pack-en
```

**Comment by ehildenb** [comment]
We're gonna try `LC_NUMERICAL`.

**Comment by Robertorosmaninho** [comment]
I still think that we can put somewhere that K needs the "en_US.UTF-8" encoding, so the user must have it available and set in their machine. Besides that, the modification LGTM!

**Review by Robertorosmaninho — APPROVED** [review]

**Comment by radumereuta** [comment]
> I still think that we can put somewhere that K needs the "en_US.UTF-8" encoding, so the user must have it available and set in their machine. Besides that, the modification LGTM!

With this modification, we don't require `en_US.UTF-8` anymore. I believe C is available on any computer, and for the rest, we don't care. Just the number format.

**Comment by Robertorosmaninho** [comment]
> With this modification, we don't require `en_US.UTF-8` anymore. I believe C is available on any computer, and for the rest, we don't care. Just the number format.

Even with this modification, having this configuration below is still possible to reproduce the `InvalidPathException`:
```
root@d910f4e6324a:/home/Rogéria# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

root@d910f4e6324a:/home/Rogéria# ../k/k-distribution/bin/kompile toto.k 
[Error] Internal: Uncaught exception thrown of type InvalidPathException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/runtimeverification/k/issues
(InvalidPathException: Malformed input or input contains unmappable characters:
/home/Rog��ria/./toto.k)
```
(This was the default encoding in my testing docker)

To reproduce it in your machine, `export LC_ALL=POSIX` should be enough.

**Comment by Baltoli** [comment]
> > With this modification, we don't require `en_US.UTF-8` anymore. I believe C is available on any computer, and for the rest, we don't care. Just the number format.
> 
> Even with this modification, having this configuration below is still possible to reproduce the `InvalidPathException`:
> 
> ```
> root@d910f4e6324a:/home/Rogéria# locale
> LANG=
> LANGUAGE=
> LC_CTYPE="POSIX"
> LC_NUMERIC="POSIX"
> LC_TIME="POSIX"
> LC_COLLATE="POSIX"
> LC_MONETARY="POSIX"
> LC_MESSAGES="POSIX"
> LC_PAPER="POSIX"
> LC_NAME="POSIX"
> LC_ADDRESS="POSIX"
> LC_TELEPHONE="POSIX"
> LC_MEASUREMENT="POSIX"
> LC_IDENTIFICATION="POSIX"
> LC_ALL=
> 
> root@d910f4e6324a:/home/Rogéria# ../k/k-distribution/bin/kompile toto.k 
> [Error] Internal: Uncaught exception thrown of type InvalidPathException.
> Please rerun your program with the --debug flag to generate a stack trace, and
> file a bug report at https://github.com/runtimeverification/k/issues
> (InvalidPathException: Malformed input or input contains unmappable characters:
> /home/Rog��ria/./toto.k)
> ```
> 
> (This was the default encoding in my testing docker)
> 
> To reproduce it in your machine, `export LC_ALL=POSIX` should be enough.

That's exactly what I'd expect to happen in the `POSIX` locale; the crash will now happen for _any_ Java application you run, not just K, so I don't think there's much else we should do to fix it.

**Comment by Baltoli** [comment]
Going to merge this as I believe we have the right fix now.

**Pull request merged**
