### PR TITLE
Miscellaneous Scala clean up

### PR DESCRIPTION
**Pull request by Scott-Guest**
This PR makes a couple quick miscellaneous changes:
- Updates `maven-compiler-plugin` and `scala-maven-plugin` to their latest versions
- Set the Java version with `<release>` rather than `<source>` and `<target>`
   - `<source>` and `<target>` only set the source code and generated class file formats, but do not take into account API changes between Java releases
   - This `<release>` tag should automatically be respected by `scala-maven-plugin` as well (once #4041 is fixed)
- Disable various Scala language extensions and enable `-Werror`
   - Not strictly necessary, but I figure this will minimize complications when we port to Scala 2.13.x and later Java
- Delete the `KORE.Att()` sugar for `Att.empty()`
   - Unrelated, the indirection just seemed pointless
- Delete `ScalaSugar`
   - It's only purpose was for implicit conversions, which requires a Scala language extension

The commit history is clean, and I recommend reviewing this one commit at a time.

### CODE REVIEW

**Review by Baltoli — APPROVED** [review]

**Comment by Baltoli** [comment]
https://github.com/NixOS/nixpkgs/pull/292323 for posterity, I implemented a feature in our backported maven builder that we can hopefully get upstreamed back into Nixpkgs

**Comment by Baltoli** [comment]
Going to hold off on merging this until @goodlyrottenapple can weigh in; the fixed-output derivation hash failure introduced in https://github.com/runtimeverification/k/pull/4055/commits/8fe2f88a86d74eb9e2e311a33f677f133b814c3c is something we've seen before with this Nix / Maven setup. As I recall, the issue is that any change to the `kore` package[^1] ends up breaking the hash because the corresponding deployed jar file ends up being deployed and re-downloaded when the FOD is built. I may be misremembering, though!

We discussed pulling this module out in #4063; doing so might be worth doing in order to make the Scala KORE parser a proper first-class dependency (and therefore avoid this problem).

[^1]: I _think_ this effect is localised to that module because the required hash doesn't change in https://github.com/runtimeverification/k/pull/4055/commits/ed0fe1f99db95931262b51c7a2715f7b85a6eabe; that commit only changes files outside of the `kore` package.

**Review by gtrepta — APPROVED** [review]
lgtm

**Comment by Baltoli** [comment]
Confirmed with @goodlyrottenapple that extracting the code we currently push as a JAR to maven repositories to its own repo, and releasing versioned JARs rather than snapshots. In the interests of letting @Scott-Guest's Scala upgrade work go through, I'm going to merge this PR even though doing so will mean dealing with hash mismatches for a few days.

**Pull request merged**
