### PR TITLE
pass the sort of the cell collection variables to the java backend

### PR DESCRIPTION
**Pull request by andreistefanescu**

### CODE REVIEW

**Comment by andreistefanescu** [comment]
@daejunpark please check if this fixes the issue with `...` in `<accounts>` in the proof specs. I tried `tests/proofs/hkg/approve-spec.k` locally, and it works.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Review by dwightguth — APPROVED** [review]

**Comment by dwightguth** [comment]
Jenkins: test this please

**Review by daejunpark — APPROVED** [review]

**Comment by daejunpark** [comment]
@andreistefanescu @dwightguth I have tested this fix, cherry-picking this on the top of the proofmodule branch, and adding the `...` in the `<accounts>` cell of the spec. It works well! Thanks!!

**Comment by dwightguth** [comment]
looks like some kind of bug in the OCAML backend was introduced by this change to SortCells. I will investigate tomorrow.

**Comment by dwightguth** [comment]
So I found a fix for the issue in the OCAML backend and I can apply that when the rest of the diff is ready, but there is some kind of much deeper bug involved here. I don't understand exactly what is going on but this change makes the java backend's associative matching algorithm break very badly, and I was able to track it down to the fact that it changes the behavior of line 73 of AssocCommToAssoc.scala, but based on that information, I have no idea how it worked previously, and my attempts at a simple fix produced very bizarre behavior, so I have to give this up. @andreistefanescu will have to investigate this further. I am going to rerun the tests now so you can see that ktest fails.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Pull request merged**
