### PR TITLE
Introduce mint-in-k 

### PR DESCRIPTION
**Pull request by Andrew-Miranti**
First step to allowing the x86 semantics to use the Ocaml backend.

### CODE REVIEW

**Comment by ehildenb** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: add to whitelist

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
I'm closing this because it's merged into the wrong branch. Please fix conflicts and reopen against the `master` branch.

**Pull request closed without merging**
