### PR TITLE
Modernized SIMPLE untyped from pl-tutorial

### PR DESCRIPTION
**Pull request by vasil-sd**
- fixed syntax
- fixed macro (except one)
- all deterministic tests were passed with llvm backend
- all non-deterministic tests were moved to attic

remaining issues:
- haskell backend is not capable to run most of non-deterministic tests. Collatz test has been executed for many hours and failed with 'killed' error (OOM killer? machine config is ryzen9 16c + 128Gb ram).

### CODE REVIEW

**Comment by ehildenb** [comment]
@vasil-sd this should be updated to:

- Make the tests still pass.
- Not update the output, instead just output the substitutions like we were doing before. You need to use the `--search` and/or `--pattern` flags to `krun` to achieve this.

**Comment by ChristianoBraga** [comment]
[IN PROGRESS] I will log my findings here and let you guys know when I am done.

1. Cloned
2. `git submodule --init --recursive`
3. `mvn package`, build successful apart from:
```shell
Running org.kframework.compile.ConstantFoldingTest
java.lang.NumberFormatException: 0.0.0
	at org.kframework.mpfr.mpfr.mpfr_set_str(mpfr.java:222)
	at org.kframework.mpfr.mpfr.mpfr_set_str(mpfr.java:191)
	at org.kframework.mpfr.BigFloat.<init>(BigFloat.java:264)
	at org.kframework.compile.FloatBuiltin.parseKFloat(FloatBuiltin.java:100)
	at org.kframework.compile.FloatBuiltin.of(FloatBuiltin.java:64)
	at org.kframework.compile.ConstantFolding.STRING_string2float(ConstantFolding.java:292)
	at org.kframework.compile.ConstantFoldingTest.testString2FloatError(ConstantFoldingTest.java:270)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Tests run: 142, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.068 sec - in org.kframework.compile.ConstantFoldingTest
```

**Comment by ehildenb** [comment]
@ChristianoBraga you can make progress by doing `mvn package -DskipTests`, so you can focus on the SIMPLE tutorial and not the unit tests.

**Comment by radumereuta** [comment]
I'm not sure why that is failing on your machine since I thought I had that covered here: https://github.com/runtimeverification/k/pull/1982
But as Everett was saying, doing `mvn package -DskipTests` will skip those tests and just build the K tool.
I do this every time since it's slightly faster anyway.

**Comment by dwightguth** [comment]
@ChristianoBraga is this still something you're trying to work on?

**Comment by ChristianoBraga** [comment]
@Dwight Guth ***@***.***> I am really behind this.
Haven't done almost nothing. I can work on this but still need some time to
put my personal life on track and catch up with KPlutus work. If it's
necessary to move on with this right now, please reassign it or close it.
Thank you.

**Comment by radumereuta** [comment]
Closing this in favor of: https://github.com/runtimeverification/k/pull/2841

**Pull request closed without merging**
