### PR TITLE
`kup` improvements

### PR DESCRIPTION
**Pull request by goodlyrottenapple**
Fixes https://github.com/runtimeverification/k/issues/2938

* `kup update <package> --version ...` and `kup install <package> --version ...` behave the same now
* `kup list <package>` fetches the git history and shows commits/tags

image

### CODE REVIEW

**Comment by ehildenb** [comment]
@goodlyrottenapple can you skip the Merge commits in the output? If that's easy, it would be nice to clean it up a bit.


Also, we should be ready to handle the pagination, but we probably don't need to yet.

**Comment by ehildenb** [comment]
Any commit with title `Merge remote-tracking branch 'origin/develop'` can be skipped basically. It would also be nice to just display one commit per version, but that can be later.

**Comment by goodlyrottenapple** [comment]
I can hard code it so that certain commits with a given prefix don't show up in the list. Bear in mind that different repositories, e.g. haskell-backend have different setup and e.g. have no version tags

**Comment by goodlyrottenapple** [comment]
> Any commit with title `Merge remote-tracking branch 'origin/develop'` can be skipped basically

done

**Comment by ehildenb** [comment]
Long term, we should probably be storing our own database with `kup` accessible versions, instead of relying on GitHub API, so we can get faster retrieval and storage of the information how we like. But for now this looks good :)

**Review by ehildenb — APPROVED** [review]

**Pull request merged**
