### PR TITLE
Fix some of the issues from Clarity on tutorial lessons

### PR DESCRIPTION
**Pull request by fiedlr**
See [my comment in Clarity on tutorial lessons](https://github.com/runtimeverification/k/issues/2033#issuecomment-1216555730) for explanation of changes.

Let me know if I should do something more for deployment.

### CODE REVIEW

**Comment by Robertorosmaninho** [comment]
308 commits?

**Comment by fiedlr** [comment]
> 308 commits?

@Robertorosmaninho Jenkins wants to push it to `develop`, I did the changes on `master`. I guess I need to transfer it to `develop` then.

**Comment by Baltoli** [comment]
@fiedlr The K CI will automatically transfer the PR target to `develop` if you open it against `master` by mistake.

**Comment by fiedlr** [comment]
@Baltoli Right... I opened a new PR that branches off of `develop` here: https://github.com/runtimeverification/k/pull/3160/files

**Pull request closed without merging**
