### PR TITLE
Refactor Kast/KRead/KPrint - less pretty printers

### PR DESCRIPTION
**Pull request by ehildenb**

### CODE REVIEW

**Comment by dwightguth** [comment]
the changes to KastFrontEnd don't make sense. You are now completely bypassing the process of selecting a default module for the parser. I can't see how tests are going to pass for this.

**Comment by ehildenb** [comment]
@dwightguth not sure what you mean, there are no semantic changes to KastFrontEnd.java, only renaming variables and formatting.

**Comment by ehildenb** [comment]
And an improved error message.

**Review by dwightguth — APPROVED** [review]
This looks like it shouldn't have any changes to behavior, which I assume is what you intended. Thus, I approve.

**Pull request merged**
