### PR TITLE
Rename the `pyk` distribution package to `kframework`

### PR DESCRIPTION
**Pull request by tothtamas28**
Related:
* #4239

Changes:
* Change `tool.poetry.name` to `kframework`
* Add `pyk` to `tool.poetry.packages`
* Update `README.md` in preparation for PyPI upload

### CODE REVIEW

**Comment by tothtamas28** [comment]
Test upload: https://test.pypi.org/project/kframework/

**Comment by tothtamas28** [comment]
~Unfortunately, the project won't install properly from PyPI because it's dependencies are not available there.~ **Edit**: https://github.com/runtimeverification/k/pull/4438#issuecomment-2162526105

A test installing the package locally:

```bash
$ poetry build
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install dist/*.whl
...
Successfully installed (...) kframework-7.x.x (...)
$ python3 -c 'import pyk'
```

Note that the distribution package is named `kframework`, but the import package is still `pyk`.

**Comment by tothtamas28** [comment]
@Baltoli, can you check if renaming the package affects the `nix` distribution?

**Comment by Baltoli** [comment]
> Unfortunately, the project won't install properly from PyPI because it's dependencies are not available there.

What's missing / can we fix this?

**Comment by tothtamas28** [comment]
> > Unfortunately, the project won't install properly from PyPI because it's dependencies are not available there.
> 
> What's missing / can we fix this?

**Edit**: bad wording in the original comment: the dependencies are not available in the PyPi _test_ repository. Pointing `pip` to both the test and main repositories allows us to test the uploaded package,

Actually, we can:

```
$ pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ kframework==7.0.1
```

The version specifier is necessary, as it seems we already have an upload in the main repo: [`kframework`](https://pypi.org/project/kframework/). (Not necessarily a bad thing, at least we can be sure we have that name reserved. :slightly_smiling_face:)

After installing the package into a virtual environment, it can be tested by importing the module:

```bash
$ python3 -c 'import pyk'
```

**Review by F-WRunTime — APPROVED** [review]

**Comment by F-WRunTime** [comment]
> After installing the package into a virtual environment, it can be tested by importing the module:

Looks good to me.

**Comment by Baltoli** [comment]
Nix seems to work fine as expected; I could point the WASM semantics to this branch and not break anything.

**Review by Baltoli — APPROVED** [review]

**Pull request merged**
