### PR TITLE
remove flaky test from ktest

### PR DESCRIPTION
**Pull request by dwightguth**
@chathhorn please review

This  test is  consistently failing on Jenkins and I just want to move forward with this without worrying about why it's failing.

I'm going to be asking you to review  K pull requests moving forward, just do your best and ask me questions where you don't understand things.

### CODE REVIEW

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by chathhorn** [comment]
Looks fine.

**Comment by dwightguth** [comment]
Jenkins:  test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Pull request merged**
