### PR TITLE
docs: :memo: Added section 2 docs

### LINKED ISSUE #3410: Missing Section 2 of K Tutorial
The [first lesson](https://github.com/runtimeverification/k/tree/master/k-distribution/k-tutorial/2_intermediate/01_macros) of the K Tutorial - Intermediate section is already available on our repository but not on our webpage. So, we'll need to create a section for this second chapter and add the first lesson there. Further, lessons will be written later and should be updated incrementally.

### PR DESCRIPTION
**Pull request by KcatMa**
Fixed #3410

### CODE REVIEW

**Comment by yiyi-wang-rv** [comment]
Please deploy the website somewhere so we can see it. And why do you delete the back quotes in the doc?

**Comment by KcatMa** [comment]
> Please deploy the website somewhere so we can see it. And why do you delete the back quotes in the doc?

OK! I have deployed it at https://kcatma.github.io/k.

I'm not sure if I should use the back-quote there because there is no use case in the entire `toc.md` now.

**Comment by yiyi-wang-rv** [comment]
Hi @radumereuta . Could you please help review @KcatMa 's  PR for the issue: https://github.com/runtimeverification/k/issues/3410
We see that there is not that much content in section 2 yet.
Thank you!

**Review by radumereuta — APPROVED** [review]
This is looking good.
Section 2 is still in progress. If we expose it to the public and we get complaints, then maybe we'll have more motivation to continue writing lessons.

**Pull request merged**
