### PR TITLE
Expose JavaExecutionOptions on command line

### PR DESCRIPTION
**Pull request by ehildenb**
@dwightguth this exposes the JavaExecutionOptions on the command-line. I attempted to mark them as experimental, but they still just show up in `--help` and not `-X`.

@denis-bogdanas you may be interested in this as well.

### CODE REVIEW

**Comment by ehildenb** [comment]
@dwightguth this is ready for review. The last two commits (1) mark the options as experimental, and (2) expose the JavaExecutionOptions to `kprove`. @denis-bogdanas helped me figure those out.

Can you take a look and let us know if it's an OK way to do this?

**Review by dwightguth — APPROVED** [review]

**Comment by ehildenb** [comment]
Jenkins: test this please

**Comment by ehildenb** [comment]
Jenkins: test this please

**Comment by denis-bogdanas** [comment]
Jenkins: test this please

**Review by dwightguth — APPROVED** [review]

**Pull request merged**
