### PR TITLE
Update macos version for Nix builds

### LINKED ISSUE #3472: Installing Nix fails on macos public runner
Possible solution: https://github.com/cachix/install-nix-action/issues/183

Failing run: https://github.com/runtimeverification/k/actions/runs/5285093409/jobs/9574749093

Logging this issue quickly for now; I'll return and investigate properly when I have time.

### PR DESCRIPTION
**Pull request by Baltoli**
Fixes #3472 for public runner builds where we use macOS images; see that original issue for a link to a failed build and associated issue on the install-nix action repo.

### CODE REVIEW

**Review by radumereuta — APPROVED** [review]

**Comment by Baltoli** [comment]
@F-WRunTime or @ehildenb will need to change the required checks here to allow this PR to go through

**Comment by jberthold** [comment]
This issue seems to have been fixed in the github action: https://github.com/cachix/install-nix-action/pull/184
Maybe we can instead bump the `install-nix-action` version to `v22` ?

**Comment by radumereuta** [comment]
> This issue seems to have been fixed in the github action: [cachix/install-nix-action#184](https://github.com/cachix/install-nix-action/pull/184) Maybe we can instead bump the `install-nix-action` version to `v22` ?

@Baltoli ^

**Comment by Robertorosmaninho** [comment]
Being fixed on #3476

**Pull request closed without merging**
