### PR TITLE
Add wrapper to Nix package to find LLVM backend

### PR DESCRIPTION
**Pull request by ttuegel**
Needed for #1733.

### CODE REVIEW

**Comment by dwightguth** [comment]
Looks fine to me but I'd like someone else to take a look since I don't know nix that well. Doesn't have to be a nix expert, I just want more eyes on this so people can start to build knowledge.

**Comment by ttuegel** [comment]
@andreiburdusa Please take a look at this.

**Comment by andreiburdusa** [comment]
Is this wrapper used to find LLVM backend like wrappers for **gcc** and **ld** are used [here](https://nixos.org/guides/nix-pills/inputs-design-pattern.html#idm140737320027952) to find **libgd**?

**Comment by ttuegel** [comment]
> Is this wrapper used to find LLVM backend like wrappers for **gcc** and **ld** are used [here](https://nixos.org/guides/nix-pills/inputs-design-pattern.html#idm140737320027952) to find **libgd**?

Yes, that's right.

**Comment by dwightguth** [comment]
What's going on with this one? Everett wanted it merged prior to my krun/kx PR, so I would like to see progress. Does @andreiburdusa still need to review? Should I just approve and merge? What's the next step and who needs to take it?

**Comment by andreiburdusa** [comment]
> What's going on with this one? Everett wanted it merged prior to my krun/kx PR, so I would like to see progress. Does @andreiburdusa still need to review? Should I just approve and merge? What's the next step and who needs to take it?

I already took a look here. I think it can be merged if @ttuegel agrees.

**Review by dwightguth — APPROVED** [review]

**Pull request merged**
