### PR TITLE
regression-new/kprove-smt-lemma: compatibility with Java backend

### PR DESCRIPTION
**Pull request by denis-bogdanas**

### CODE REVIEW

**Comment by daejunpark** [comment]
Is this test run on the java backend as well?  If not, could you please make it run on both backends?  Thanks!

**Comment by denis-bogdanas** [comment]
Done

**Comment by daejunpark** [comment]
Thanks, but could you please reorg the directory to follow the existing standard, like https://github.com/kframework/k/tree/62f28a66d89f936e630704b1f7f7b8aa6c6d70fd/k-distribution/tests/regression-new/rat/defined ?

**Comment by denis-bogdanas** [comment]
@daejunpark done

**Review by daejunpark — APPROVED** [review]
Thanks!

**Pull request merged**
