### PR TITLE
add new hook names for crypto hooks

### PR DESCRIPTION
**Pull request by dwightguth**
@ttuegel @sskeirik FYI

This is done in order to separate the crypto hooks out based on which native library they depend on in the llvm backend, in order to simplify the build process for new semantics. The old hooks will remain valid for the time being for backwards-compatibility.

### CODE REVIEW

**Comment by ehildenb** [comment]
Have these hooks been added to the LLVM backend? Are we planning on incorporating the hooks from blockchain-k-plugin directly into the LLVM backend?

**Comment by dwightguth** [comment]
No, these hooks are not part of the llvm backend because that would involve making developers install obscure Bitcoin and cryptography libraries in order to build the k frontend. It's not an issue with java and haskell because their package managers pull in the right libraries automatically.

**Comment by ehildenb** [comment]
Ah sorry, I misread, forgot that this is only for the Java backend. Approving.

**Review by ehildenb — APPROVED** [review]

**Comment by ehildenb** [comment]
Though I guess someone who needs this should approve as well.

**Comment by sskeirik** [comment]
EDIT: TL;DR version --- I vote we change `HASH.sha3` hook to `HASH.sha3_256`.

Since we are changing hook names anyway, I propose the LLVM backend migrates from the name `sha3` to `sha3256` like the Haskell and Java backends or else something like `sha3_256`. I didn't think about changing that before since it wasn't a hook that I was adding, but I do think it makes sense to keep the digest size in bits after each hash function, for consistency of naming and also clarity. Thus, under this naming scheme we have either:

hash function name + digest size

hash function name + (separator when hash name ends with number) + digest size

**Comment by dwightguth** [comment]
As far as I can tell, the build failed because github was experiencing problems. I restarted it.

**Pull request merged**
