### PR TITLE
Use macos-11 instead of macos-latest in github actions

### PR DESCRIPTION
**Pull request by andreiburdusa**
Fixes: runtimeverification/iog-pm#54

Try using `macos-11` because `macos-latest` is no longer the latest

### CODE REVIEW

**Comment by ehildenb** [comment]
@andreiburdusa any updates on this?

**Comment by andreiburdusa** [comment]
> @andreiburdusa any updates on this?

It looks like GitHub hasn't enabled macos-11 for public use yet. We can try again later, as discussed in [this slack thread](https://runtimeverification.slack.com/archives/C7E701MFG/p1624901386325900)

**Comment by ehildenb** [comment]
Ok, that's fine. But @andreiburdusa can you link to some GitHub documentation about this one, so it's easier to track?

**Comment by andreiburdusa** [comment]
Maybe this https://github.com/actions/virtual-environments/pull/3748 is relevant?

**Comment by radumereuta** [comment]
Let's see if this is available now.
@andreiburdusa can we have an update on this?

**Comment by radumereuta** [comment]
Is this ready to be merged now?
If yes, could you please ask for reviewers?

**Review by radumereuta — APPROVED** [review]

**Pull request merged**
