### PR TITLE
Add `--kore-rpc-command` option to `pyk prove`

### PR DESCRIPTION
**Pull request by geo2a**
Somehow the `--kore-rpc-command` option has disappeared from `pyk prove`, so this PR is bringing it back.

### CODE REVIEW

**Comment by ehildenb** [comment]
@geo2a you need to rebase on `develop` directly, and remove the changes that came in from `master`.

**Comment by ehildenb** [comment]
Also, please have @nwatson22 confirm that this is the intended way to use the CLI. He designed the new parameter system, and I believe it requires more changes than this.

**Comment by geo2a** [comment]
Thanks @ehildenb, I've rebased and force-pushed.

@nwatson22 could you have a look at the PR and advise if I need to add the argument somehow differently? Also, I'd appreciate an advice on how to add `--bug-report` to `pyk prove`.

**Comment by nwatson22** [comment]
This looks good. The `--kore-rpc-command` option seems to have just been removed from the argparse section, not from `ProveOptions`, so I don't think anything else needs to be done. To add `--bug-report`, I would add `k_cli_args.bug_report_args` to the parents here:
```
    prove_args = pyk_args_command.add_parser(
        'prove',
        help='Prove an input specification (using RPC based prover).',
        parents=[k_cli_args.logging_args, k_cli_args.spec_args, config_args.config_args],
    )
```
and add `BugReportOptions` to the list of inherited classes in `ProveOptions` here:
```
class ProveOptions(LoggingOptions, SpecOptions, SaveDirOptions):
```

**Review by nwatson22 — APPROVED** [review]

**Comment by geo2a** [comment]
Thanks @nwatson22!

**Pull request merged**
