### PR TITLE
split BYTES into concrete and symbolic implementation

### PR DESCRIPTION
**Pull request by dfilaretti**
With this change, we are able to kompile IELE for the Haskell backend.

### CODE REVIEW

**Review by dwightguth — CHANGES_REQUESTED** [review]
you definitely should not have deleted the rules for Int2Bytes in the BYTES module.

**Comment by dfilaretti** [comment]
Oh wow, looks like not only I deleted those rules, but also the `endmodule`. 
Clearly this happened while I was trying to figure out why `git` wouldn't allow me to push, ending up copying/pasting my changes several times on different repos etc. Should be fine now.

**Comment by daejunpark** [comment]
a general question. how do you ensure that the hooked implementation agrees with the k rules? is it a trust base?

**Comment by dwightguth** [comment]
I mean, we have tests, but yeah, it's not formally guaranteed by anything.

**Comment by dfilaretti** [comment]
@dwightguth Are you happy with the fix? Can I merge it?

**Review by dwightguth — APPROVED** [review]
looks good but please make sure that iele passes tests with this version of k before you merge.

**Comment by dfilaretti** [comment]
Yes I tried running IELE tests (`make vm-test`) and it looks fine.

**Comment by dfilaretti** [comment]
Jenkins: please test this

**Comment by dfilaretti** [comment]
Not sure what's going on here but it seems to be stuck on Jenkins tests ("default Expected — Waiting for status to be reported")

Also, it says "This pull request can be automatically merged by project collaborators
Only those with write access to this repository can merge pull requests." so I'm not sure I have the required permissions...

**Comment by dwightguth** [comment]
The build is in the queue right now, be patient.

**Comment by dfilaretti** [comment]
Looks like those checks are still pending...

screen

**Comment by dfilaretti** [comment]
Jenkins: test this please

**Comment by dfilaretti** [comment]
Cool, it did work this time!

**Pull request merged**
