### PR TITLE
Modify BMC unknown output to top.

### PR DESCRIPTION
**Pull request by yzhang90**

### CODE REVIEW

**Comment by ehildenb** [comment]
@yzhang90 this bumps the submodule to a branch of haskell backend that is not behind master, so cannot be merged. Please back out the haskell backend submodule update, get your haskell backend PR merged, and then get this merged in the resulting update-deps job that is opened.

**Comment by yzhang90** [comment]
@ehildenb Tom just want to make sure that the udpate to the haskell backend doesn't break K's integration tests. I'll update this PR when the change to the haskell backend is merged.

**Comment by yzhang90** [comment]
@ehildenb please review again.

**Comment by ttuegel** [comment]
Merged into #1736.

**Pull request closed without merging**
