### PR TITLE
Added some documentation for RHS vars usage scenarios

### PR DESCRIPTION
**Pull request by traiansf**

### CODE REVIEW

**Comment by dwightguth** [comment]
This attribute seems sketchy to me. Wouldn't it be better if we had some way of marking individual variables as universally quantified on the rhs?

**Comment by traiansf** [comment]
> This attribute seems sketchy to me. Wouldn't it be better if we had some way of marking individual variables as universally quantified on the rhs?

I agree. I only put it there as a placeholder, in some sense.  There was no agreement on such a label.

How about something like `rhs-only(X, Y)` ?

**Comment by traiansf** [comment]
@dwightguth I've updated the documentation to match the `unboundVariables` attribute introduced in the other PR. could you please take another look at it?

**Review by dwightguth — APPROVED** [review]

**Comment by dwightguth** [comment]
This looks good to me but I'd like someone from the haskell backend to review it also.

**Review by ttuegel — APPROVED** [review]
This seems alright to me, but why not require explicit quantification with `#Forall`?

**Comment by traiansf** [comment]
> This seems alright to me, but why not require explicit quantification with `#Forall`?

I guess it would make it harder to write; moreover, all variables are implicitly universally quantified; why quantify some and not others?

**Comment by ttuegel** [comment]
> all variables are implicitly universally quantified

Well, except for the ones that are now banned! :smiley:

**Comment by dwightguth** [comment]
Well, there are cases where you want a variable on the RHS that is unbound that will become bound later, like the rhs of a macro that is used on the lhs, so if you required explicit quantification, then you would have to somehow delete that quantifier later, which would be kinda messy.

**Pull request merged**
