### PR TITLE
Priority filter fix.

### LINKED ISSUE #1593: [Bug] kprove - Cannot use #Forall as a child of #And
K Version
---------

```
$ /home/andrei/kore/.build/k/bin/kompile  --version
RV-K version 1.0-SNAPSHOT
Git revision: 5e4e023
Git branch: UNKNOWN
Build date: Wed Sep 09 17:51:33 EEST 2020
```

Description
-----------

Running `kprove` with the following files causes a parsing error.

Input Files
-----------

File: `test.k`

```
module TEST
    imports BOOL
    imports INT

    syntax Exp ::= Int | Bool
                 | pair(Int, Int) [klabel(pair), symbol]

    syntax KItem ::= "#assume" Exp [klabel(assume), symbol]
    rule #assume true => .K
    rule #assume false => #Bottom

    syntax KItem ::= "#assert" Exp  [klabel(assert), symbol]
                   | "#fail"
    rule #assert true => .K
    rule #assert false => #fail

// Uninterpreted functions
    syntax Int ::= i(Int, Int)   [function, functional, no-evaluators, smtlib(fi), klabel(i)]
    syntax Int ::= p(Exp, Int)   [function, functional, no-evaluators, smtlib(fp), klabel(p)]
endmodule
```

File: `issue-2138.spec.k`

```
module VERIFICATION
  import TEST
endmodule

module ISSUE-2138-SPEC
  import VERIFICATION

  rule
    <k> #assert i ( 1 , 0 ) ==Int 0 => . </k>
      requires true #And #Forall X. { i ( X, 0 ) #Equals 0 }

endmodule
```

Reproduction Steps
------------------

Running the spec produces an error:

```
$ /home/andrei/kore/.build/k/bin/kprove --haskell-backend-command /home/andrei/kore/.build/kore/bin/kore-exec -d . -m VERIFICATION issue-2138-spec.k
[Error] Inner Parser: Priority filter exception. Cannot use #Forall as a child
of #And
	Source(/home/andrei/kore/test/issue-2138/././issue-2138-spec.k)
	Location(10,28,10,63)
[Error] Compiler: Had 1 parsing errors.
```

Expected Behavior
-----------------

The spec should be run successfully.

### PR DESCRIPTION
**Pull request by radumereuta**
Fixes: #1593
Allow for left guarded and right guarded operators under binary operators

### CODE REVIEW

**Comment by dwightguth** [comment]
I'm going to need to see some kind of peer reviewed source indicating that this is a safe change to make and won't introduce ambiguities before I agree to it.

**Comment by radumereuta** [comment]
https://homepages.cwi.nl/~jurgenv/papers/SLE2013-1.pdf
Page 5, first paragraph you have a small example.
In the paper, they have a much more general approach which allows them to disambiguate more, but the algorithm is more complex. They duplicate productions and I think it might slow down our parser even further. I only picked up the part where left and right guarded productions are safe to use with binary operators.

I was a bit surprised by this issue since I thought this was the default behavior, but apparently, a long time ago I ran into some issues with FUN and forgot about it.

**Comment by dwightguth** [comment]
So, the paragraph you refer me to tells me why the grammar we are encountering is not ambiguous and why the priority mechanism as written is problematic on this example, but it doesn't tell me that the solution that you provide here is safe.

**Comment by radumereuta** [comment]
I'm not sure why this is failing, let's try again.

**Pull request closed without merging**
