### PR TITLE
Print intermediate timing information about backend steps

### PR DESCRIPTION
**Pull request by radumereuta**
Helps with profiling and debugging.

Output from the C-semantics: (llvm)
```
Kompile to kore                                              =  2.594s
Save to disk                                                 =  0.892s
  Print definition.kore                                      =  9.046s
  Write decision tree                                        = 14.679s
  Executing in /home/radu/work/c-semantics/.build/dist/lib/kcc/llvm/c-kompiled: llvm-kompile definition.kore dt main -o interpreter -g -c -o interpreter.o
  interpreter: main                                          = 31.496s
Backend                                                      = 55.222s
```
kompile test.k --backend llvm --enable-search
```
Save to disk                                                 =  0.029s
  Print definition.kore                                      =  0.088s
  Write decision tree                                        =  0.566s
  Executing in /home/radu/work/test/test-kompiled: llvm-kompile definition.kore dt main -o interpreter
  interpreter: main                                          =  0.207s
  Executing in /home/radu/work/test/test-kompiled: llvm-kompile definition.kore dt search -o search
  search: search                                             =  0.497s
Backend                                                      =  1.362s
```
kompile test.k --backend haskell
```
Save to disk                                                 =  0.079s
  Print definition.kore                                      =  0.116s
  Validate def                                               =  0.270s
Backend                                                      =  0.387s
```

I was working with @sskeirik on trying to debug some excessive memory usage, and these printouts could help us pinpoint which stage is taking a long time and uses too much memory.

### CODE REVIEW

**Comment by dwightguth** [comment]
This is good, but I don't like the look of that long line there. Can we shorten it somehow? I don't want to risk having lines wrap on the terminal here as that will make it much harder to read.

**Comment by radumereuta** [comment]
I didn't touch that line. To make it worse, here is what KEVM spits out:
```
Save to disk                                                 =  0.189s
  Print definition.kore                                      =  1.434s
  Write decision tree                                        =  2.837s
  Executing in /home/radu/work/evm-semantics/.build/usr/lib/kevm/llvm: llvm-kompile definition.kore dt main -o interpreter -L/home/radu/work/evm-semantics/.build/usr/lib/kevm/libff/lib -I/home/radu/work/evm-semantics/.build/usr/lib/kevm/libff/include /home/radu/work/evm-semantics/.build/usr/lib/kevm/blockchain-k-plugin/include/c/plugin_util.cpp /home/radu/work/evm-semantics/.build/usr/lib/kevm/blockchain-k-plugin/include/c/crypto.cpp /home/radu/work/evm-semantics/.build/usr/lib/kevm/blockchain-k-plugin/include/c/blake2.cpp -g -std=c++14 -lff -lcryptopp -lsecp256k1 -lssl -lcrypto -lprocps
  interpreter: main                                          =  6.743s
Backend                                                      = 11.015s
```
Suggestions?

**Comment by dwightguth** [comment]
Ah. If that hasn't changed, let's just leave it alone for now. We can address it separately if people complain.

**Review by dwightguth — CHANGES_REQUESTED** [review]
I'm pretty sure it ought to be possible to do this with just one extra stopwatch in each backend

**Comment by radumereuta** [comment]
> I'm pretty sure it ought to be possible to do this with just one extra stopwatch in each backend

You are correct. Fixed it.

**Review by Baltoli — APPROVED** [review]

**Comment by Baltoli** [comment]
> Suggestions?

If people complain I can implement a line-length capped version that inserts the correct line continuation characters. Not introduced in this PR though, as @radumereuta says, so I'm happy to leave it for now.

**Review by dwightguth — APPROVED** [review]

**Comment by radumereuta** [comment]
I've rebased onto develop and updated the output to better highlight matching printouts. @ehildenb take a look.
```
Save to disk                                                 =  0.027s
  Print definition.kore                                      =  0.088s
  Write decision tree                                        =  0.601s
  ┌Executing in /home/radu/work/test/test-kompiled: llvm-kompilex definition.kore dt main -- -o interpreter
  └interpreter: main                                         =  0.218s
  ┌Executing in /home/radu/work/test/test-kompiled: llvm-kompilex definition.kore dt search -- -o search
  └search: search                                            =  0.484s
Backend                                                      =  1.392s
```

**Pull request merged**
