### PR TITLE
Hotfix/maven release push

### PR DESCRIPTION
**Pull request by F-WRunTime**
This is a new change / setup to test the Workflow release.yaml. The release now appears to be working after resetting and changing all passwords.

### CODE REVIEW

**Comment by F-WRunTime** [comment]
Test being run: https://github.com/runtimeverification/k/actions/runs/5824898448/job/15795093670#step:6:6
Variables and secrets are obfuscated in logs 
```bash
cat ~/.m2/settings.xml
  docker exec -t k-release-ci-${GITHUB_SHA} bash -c 'mkdir -p /home/github-runner/.m2'
  docker cp ~/.m2/settings.xml k-release-ci-${GITHUB_SHA}:/tmp/settings.xml
  docker exec -t k-release-ci-${GITHUB_SHA} bash -c 'mv /tmp/settings.xml /home/github-runner/.m2/settings.xml'
  docker exec -e MAVEN_USERNAME -e MAVEN_PASSWORD -t k-release-ci-${GITHUB_SHA} bash -c "mvn --batch-mode deploy"
  shell: /usr/bin/bash {0}
  env:
    JAVA_HOME: /home/github-runner/actions-runner/_work/_tool/Java_Adopt_jdk/11.0.20-8/x64
    JAVA_HOME_11_X64: /home/github-runner/actions-runner/_work/_tool/Java_Adopt_jdk/11.0.20-8/x64
    MAVEN_USERNAME: devops@runtimeverification.com
    MAVEN_PASSWORD: ***
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w[3](https://github.com/runtimeverification/k/actions/runs/5824898448/job/15795093670#step:6:3).org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
      <id>runtime.verification.snapshots</id>
      <username>${env.MAVEN_USERNAME}</username>
      <password>${env.MAVEN_PASSWORD}</password>
    </server>
  </servers>
</settings>[INFO] Scanning for projects...
```

**Comment by F-WRunTime** [comment]
- [x] Waiting on Test to Pass https://github.com/runtimeverification/k/actions/runs/5824898448

**Comment by F-WRunTime** [comment]
#https://github.com/runtimeverification/k/actions/runs/5824898448

**Review by dwightguth — APPROVED** [review]

**Comment by dwightguth** [comment]
We believe with configuration changes to the github repo, the release should now work correctly. We need to merge this PR in order to trigger the release workflow.

**Pull request merged**
