### PR TITLE
Outer: remove redundancy in parser error message

### PR DESCRIPTION
**Pull request by SchmErik**
Consider the following files:
primay.k:

```k
requires "secondary.k"

module PRIMARY

  syntax Foo ::= "bar"

endmodule
```

secondary.k:

```k
module SECONDARY

  syntax Foo ::= | "baz"

endmodule
```

When compiling primary.k, the following error message is generated:
```
  [Error] Outer Parser: Encountered "|".
  Was expecting one of: ["non-assoc", <STRING>, <STRING_REGEX>, "(", "left",
  "right", "List", "NeList", <UPPER_ID>, <LOWER_ID>, <NAT>, <UPPER_ID>, "List",
  "NeList", <LOWER_ID>] (ParseException: Encountered " "|" "|"" at line 3, column
  18.

  Was expecting one of:

  "non-assoc" ...
      <STRING> ...
      <STRING_REGEX> ...
      "(" ...
      "left" ...
      "right" ...
      "List" ...
      "NeList" ...
      <UPPER_ID> ...
      <LOWER_ID> ...
      <NAT> ...
      <UPPER_ID> ...
      "List" ...
      "NeList" ...
      <LOWER_ID> ...
      )
  	Source(/home/erik/samps-k/secondary.k)
  	Location(3,18,3,18)
```

This error message's "ParseException: ..." message is redundant. Remove
the redundancy by adding a boolean field to the KException class and
overloading several other methods to create KException objects that do
not print exception messages that are redundant to the actual error
messages. Doing so shortens the previous error message to look like this:
```
  [Error] Outer Parser: Encountered "|".
  Was expecting one of: ["non-assoc", <STRING>, <STRING_REGEX>, "(", "left",
  "right", "List", "NeList", <UPPER_ID>, <LOWER_ID>, <NAT>, <UPPER_ID>, "List",
  "NeList", <LOWER_ID>]
  	Source(/home/erik/samps-k/secondary.k)
  	Location(3,18,3,18)
```

Signed-off-by: Erik Kaneda <erik.kaneda@runtimeverification.com>

### CODE REVIEW

**Comment by ehildenb** [comment]
Please add a test it `k-distribution/tests/regression-new/checks` for this new error message.

**Review by dwightguth — COMMENTED** [review]
Looks great! Good work! I agree we should add a test though.

**Comment by SchmErik** [comment]
I added a test in a separate commit just now

**Review by radumereuta — APPROVED** [review]

**Comment by radumereuta** [comment]
Fixes: #2100

**Pull request merged**
