### PR TITLE
Adding kast option keepAmb

### PR DESCRIPTION
**Pull request by radumereuta**
Since we made ambiguities report as errors, I'm adding this option to kast to visualize ambiguous programs better.

### CODE REVIEW

**Comment by radumereuta** [comment]
This is the second step in solving #828.

**Comment by dwightguth** [comment]
What is this actually used for? If it's just for describing ambiguities to users, why isn't the error message enough data?

**Comment by radumereuta** [comment]
Sometimes, seeing the entire AST can be more descriptive.
Also, Grigore had plans at one point to do disambiguation with K rules. Since we're eliminating the ambiguities, we have no way of doing that. We'd have to rely on external parsers.

**Comment by radumereuta** [comment]
After discussing with Dwight, we decided that: either the error message contains sufficient information to resolve the ambiguity, in which case we shouldn't need this feature, or it doesn't, in which case we should fix the error message.

We'll wait and see if the users complain about ambiguities being errors and proceed then.

**Pull request closed without merging**
