### PR TITLE
Fix GeneratedCounterCell location

### LINKED ISSUE #3348: `generatedCounter` should be the last cell of `generatedTop`
Consider the following definition:

```
module TEST-SYNTAX
    imports INT-SYNTAX
endmodule

module TEST
    imports TEST-SYNTAX
    configuration
        <k> $PGM:Int </k>
        <a> $A:Int </a>
        <b> $B:Int </b>
        <c> $C:Int </c>
endmodule
```

when kompiled, the following production is generated:

```k
syntax GeneratedTopCell ::= "<generatedTop>" KCell ACell BCell GeneratedCounterCell CCell "</generatedTop>" [...]
```

That is, `GeneratedCounterCell` gets wedged between `BCell` and `CCell`, which seems random. Instead, one would expect `GeneratedCounterCell` to be the last production item:

```k
syntax GeneratedTopCell ::= "<generatedTop>" KCell ACell BCell CCell GeneratedCounterCell "</generatedTop>" [...]
```

This makes programmatic processing of the configuration more straightforward.

### PR DESCRIPTION
**Pull request by radumereuta**
Make the GeneratedCounterCell location more consistent.
Before:
```
syntax GeneratedTopCell ::= "<generatedTop>" KCell ACell BCell GeneratedCounterCell CCell "</generatedTop>" [...]
```
After:
```
syntax GeneratedTopCell ::= "<generatedTop>" KCell ACell BCell CCell GeneratedCounterCell "</generatedTop>" [...]

```
Fixes: #3348

### CODE REVIEW

**Comment by radumereuta** [comment]
@ehildenb you were right. You wrote this step: `GeneratedTopFormat` which fixes the formatting and gets called after the fact.
I added comments in the code so that next time I can find it easier.

**Comment by ehildenb** [comment]
This isn't really the fix we discussed is it? We instead wanted to move the generation of the `format` attribute to after the entire configuration is resolved?

**Comment by ehildenb** [comment]
Was this also tested on a configuration that has a topmost cell already existing?

**Comment by radumereuta** [comment]
Here is how it looks for a config with a <T> cell and w/o:
```
configuration <T> <k> $PGM:Int </k> <a> $A:Int </a> <b> $B:Int </b> <c> $C:Int </c> </T>
syntax GeneratedTopCell ::= "<generatedTop>" TCell GeneratedCounterCell "</generatedTop>" [cell, cellName(generatedTop), format(%2), topcell]

configuration <k> $PGM:Int </k> <a> $A:Int </a> <b> $B:Int </b> <c> $C:Int </c>
syntax GeneratedTopCell ::= "<generatedTop>" KCell ACell BCell CCell GeneratedCounterCell "</generatedTop>" [cell, cellName(generatedTop), format(%1%i%n%2%n%3%n%4%n%5%d%n%7), org.kframework.definition.Production(syntax #RuleContent ::= #RuleBody [klabel(#ruleNoConditions), symbol]), topcell]
```
Formatting looks right to me, and all tests are still passing.

I added another commit to extract the step, which fixes the formatting.
Hopefully, this will make it more visible.
This is applied after the steps which modify the productions generated from the configuration.

**Review by tothtamas28 — COMMENTED** [review]
I'm fine with any solution that fixes the original bug. @ehildenb had some comments on architecture though, so I'll let him approve this one.

**Review by ehildenb — APPROVED** [review]

**Pull request merged**
