### PR TITLE
Fix a typo in the K standard library

### PR DESCRIPTION
**Pull request by amelieled**
funtional -> total

### CODE REVIEW

**Review by dwightguth — APPROVED** [review]

**Comment by dwightguth** [comment]
You need to change the target branch of this PR to the develop branch. The code looks good though.

**Comment by Baltoli** [comment]
I don't think this PR will run properly as it's been made from a fork @amelieled; you'll need to open it from a branch on the K repo instead.

**Comment by dwightguth** [comment]
@Baltoli that's not the issue. I don't see any reason why you wouldn't be able to make a PR from a fork, because that's the norm for contributors who aren't maintainers. The issue is the target branch is wrong.

**Comment by amelieled** [comment]
Sorry @Baltoli , I can't create a branch.
Sorry @dwightguth , I can't change the source branch. 
I mean, GitHub interface forces me to do my modifications on `runtimeverification:master`. I will try tomorrow to do it from my terminal.
Btw, what is the difference between `runtimeverification:master` and `master`? The first one, doesn't exist, right?

**Comment by Baltoli** [comment]
> @Baltoli that's not the issue. I don't see any reason why you wouldn't be able to make a PR from a fork, because that's the norm for contributors who aren't maintainers. The issue is the target branch is wrong.

CI won't run because fork PRs don't get access to our Github tokens. You can see this happening on the failure for the "Change base to develop branch" action, but it would be the same situation were the PR to be opened against `develop` initially as the token is required in other places.

@F-WRunTime can confirm what the correct solution is here.

**Comment by amelieled** [comment]
I'm lost and blocked: what I'm supposed to do?

**Comment by Baltoli** [comment]
Someone needs to add you to the RV organisation so that you can push a branch to this repo and have CI run your pull request, rather than working from a fork.

I don't have the permissions to do so - I think @dwightguth @ehildenb @F-WRunTime can?

**Comment by ehildenb** [comment]
@amelieled you'll need to do the following:

- Rebase your singlne commit on the `develop` branch, not on the `master` branch (need to target PRs against develop branch on this repo, not default master branch).
- I've already changed the merge base to `develop`, not `master`.

**Comment by amelieled** [comment]
Thanks @ehildenb !
I've just started again the PR here: #3192 :crossed_fingers:

**Pull request closed without merging**
