### PR TITLE
Fix regression in java backend about sort of poly productions

### PR DESCRIPTION
**Pull request by dwightguth**
Ready for review.

### CODE REVIEW

**Review by traiansf — APPROVED** [review]

**Comment by ehildenb** [comment]
Let me try SBC on this before merging.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
@ehildenb says this doesn't fix SBC, but I'm going to merge so that we can get the fix for EVM deployed. @ehildenb , if you can point me in the direction of a reproducible failure, I can investigate the other issue if you want.

**Pull request merged**
